'use client';
import { useState } from 'react';
import { addCatalogItemWithContainment, readCatalogCart } from '@/lib/catalog-cart';
import PartnerOfferCard, { type PublicOffer } from './PartnerOfferCard';

type Product = {
  id:string; type:string; slug:string; name:string; aliases?:string[]; description?:string|null;
  preparation?:string|null; imageData?:string|null; fastingNeeded:boolean; fastingHours?:number|null;
  parameterCount?:number|null; sampleTypes:string[]; categories?:{slug:string;name:string;description?:string|null}[];
  offers:PublicOffer[]; includedTestCount?:number; includedTests?:{id:string;slug:string;name:string}[];
  tests?:{slug:string;name:string}[];
  includedProfiles?:{id:string;slug:string;name:string;parameterCount?:number|null;includedTests:{id:string;slug:string;name:string}[]}[];
};
function fastingText(product:Product){if(!product.fastingNeeded)return 'Fasting information not recorded; confirm before collection';return product.fastingHours?`${product.fastingHours} hours fasting recorded`:'Fasting required; confirm duration before collection';}
function safeImage(value?:string|null){if(!value)return null;const trimmed=value.trim();if(/^data:image\/(?:png|jpeg|jpg|webp|gif);base64,/i.test(trimmed))return trimmed;if(/^https:\/\//i.test(trimmed))return trimmed;return null;}
const aarogyamCampReportParameters:Record<string,string[]>={
 'thyrocare-profile-lipid-53':['LDL / HDL Ratio','NON-HDL Cholesterol','TC / HDL Cholesterol Ratio','VLDL Cholesterol','HDL / LDL Ratio','TRIG / HDL Ratio'],
 'thyrocare-profile-lft-54':['Bilirubin - Indirect','Serum Albumin / Globulin Ratio','SGOT / SGPT Ratio'],
 'thyrocare-profile-kidpro-49':['BUN / Creatinine Ratio','Urea / SR. Creatinine Ratio'],
 'thyrocare-profile-diabetes-aacp1':['Average Blood Glucose (ABG)'],
 'thyrocare-profile-cardiac-risk-aacp2':['ApoB / ApoA1 Ratio'],
 'thyrocare-profile-ironpro-47':['% Transferrin Saturation','Unsat. Iron-binding Capacity (UIBC)'],
};
const aarogyamCampPackageIds=new Set(['thyrocare-package-aacp1-33','thyrocare-package-aacp2-34','thyrocare-package-acp3-35','thyrocare-package-aa1-2wu-2','thyrocare-package-aa1-3wu-3','thyrocare-package-aa1-4wu-4','thyrocare-package-aa1-5wu-5']);
type IncludedProfile=NonNullable<Product['includedProfiles']>[number];
function includedProfileDisplayName(productId:string,profile:IncludedProfile){
 if((productId==='thyrocare-package-aacp2-34'||productId==='thyrocare-package-acp3-35'||productId==='thyrocare-package-aa1-3wu-3'||productId==='thyrocare-package-aa1-4wu-4'||productId==='thyrocare-package-aa1-5wu-5')&&profile.id==='thyrocare-profile-vdtab12c-87')return 'VITAMIN PROFILE';
 if((productId==='thyrocare-package-aa1-4wu-4'||productId==='thyrocare-package-aa1-5wu-5')&&profile.id==='thyrocare-profile-seel-69')return 'ELECTROLYTES PROFILE';
 return profile.name;
}
export default function CatalogDetail({product}:{product:Product}){
 const [added,setAdded]=useState(false); const [alreadyIncluded,setAlreadyIncluded]=useState(false); const [showAllTests,setShowAllTests]=useState(false); const [showDetailsImage,setShowDetailsImage]=useState(false); const [openProfileIds,setOpenProfileIds]=useState<string[]>([]);
 function add(offer:PublicOffer,pincode:string){const key='tglabs-cart';const cart=readCatalogCart(localStorage.getItem(key));const item={productType:product.type as 'TEST'|'PROFILE'|'PACKAGE',productIdentifier:product.id,productName:product.name,offerIdentifier:offer.offerId,partnerIdentifier:offer.partner.slug,partnerName:offer.partner.name,tat:offer.tat??null,mrp:offer.mrp??null,displayedPrice:offer.price,pincode};const composition=new Map<string,readonly string[]>();if(product.type!=='TEST')composition.set(product.id,(product.includedTests??[]).map(test=>test.id));const result=addCatalogItemWithContainment(cart,item,composition);if(result.status==='already-included'){setAdded(false);setAlreadyIncluded(true);return;}localStorage.setItem(key,JSON.stringify(result.items));setAlreadyIncluded(false);setAdded(true);window.dispatchEvent(new Event('tglabs-cart-updated'));}
 const lowestPrice=product.offers.length?Math.min(...product.offers.map(offer=>offer.price)):null;
 const includedTests=product.includedTests??[];
 const includedTestCount=product.includedTestCount??includedTests.length; const derivedParameterCount=product.parameterCount?Math.max(0, Number(product.parameterCount)-includedTestCount):0;
 const visibleTests=showAllTests?includedTests:includedTests.slice(0,8);
 const detailsImage=safeImage(product.imageData);
 const itemNoun=product.type==='PROFILE'?'profile':product.type==='PACKAGE'?'package':'test';
 const itemNounTitle=itemNoun[0].toUpperCase()+itemNoun.slice(1);
 const measureVerb=product.type==='TEST'?'measure?':'include?';
 return <main className="testDetailPage">
  <nav className="testBreadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>›</span><span>{product.type==='PROFILE'?'Profiles':product.type==='PACKAGE'?'Packages':'Tests'}</span><span>›</span><span aria-current="page">{product.name}</span></nav>
  <header className="testHero"><div className="testHeroCopy"><div className="testEyebrow">Diagnostic {itemNoun}</div><h1>{product.name}</h1>{product.aliases?.length?<p className="testAliases">Also known as: {product.aliases.slice(0,4).join(', ')}</p>:null}{product.categories?.length?<div className="testCategories">{product.categories.map(category=><a key={category.slug} href={`/categories/${category.slug}`}>{category.name}</a>)}</div>:null}
  {detailsImage ? <button type="button" className="testDetailsImageLink" onClick={()=>setShowDetailsImage(true)}>View {itemNoun} details</button> : null}</div>
  <aside className="testHeroPrice" aria-label="Booking summary"><span>Available from</span><strong>{lowestPrice!==null?`₹${lowestPrice}`:'Check partner price'}</strong><small>{product.offers.length} eligible lab partner{product.offers.length===1?'':'s'}</small><a href="#lab-partners" className="testPrimaryCta">Compare labs &amp; book</a></aside></header>
  <section className="testOverviewCard"><div className="sectionHeading"><span>About {itemNoun}</span><h2>What does {product.name} {measureVerb}</h2></div><p className="testDescription">{product.description||`A patient-friendly educational overview is being prepared for this ${itemNoun}.`}</p><p className="educationNotice">This overview is educational. Use the recorded preparation, sample and lab-partner details below for collection guidance, and confirm any missing information before collection.</p></section>
  <section className="testQuickFacts" aria-label={`${itemNounTitle} preparation and sample details`}><article><span>Sample required</span><strong>{product.sampleTypes.length?product.sampleTypes.join(', '):'Sample information not recorded; confirm before collection'}</strong></article><article><span>Fasting</span><strong>{fastingText(product)}</strong></article><article><span>Preparation</span><strong>{product.preparation?.trim()||'Preparation information not recorded; confirm before collection'}</strong></article>{product.parameterCount?<article><span>Parameters</span><strong>{product.parameterCount}</strong></article>:null}</section>
  {product.type==='PACKAGE'&&product.includedProfiles?.length?<section className="testContentSection"><div className="sectionHeading"><span>Included profiles</span><h2>{product.parameterCount ? `${product.parameterCount} parameters across ${product.includedProfiles.length} profiles${includedTestCount?` + ${includedTestCount} individual tests`:''}` : `${product.includedProfiles.length} profiles`}</h2><p>Open a profile to see the verified individual tests currently available in the catalog. The profile parameter total includes calculated or report parameters and is not double-counted.</p></div><div className="includedProfiles">{product.includedProfiles.map(profile=>{const isOpen=openProfileIds.includes(profile.id);return <article key={profile.id} className="includedProfile"><button type="button" className="testSecondaryCta" aria-expanded={isOpen} aria-controls={`profile-tests-${profile.id}`} onClick={()=>setOpenProfileIds(current=>current.includes(profile.id)?current.filter(id=>id!==profile.id):[...current,profile.id])}><strong>{includedProfileDisplayName(product.id,profile)}</strong>{profile.parameterCount?<span> · {profile.parameterCount} parameters</span>:null}<span className="includedProfileAction">{isOpen?'− Hide tests':'+ View tests'}</span></button>{isOpen?<div id={`profile-tests-${profile.id}`}>{profile.includedTests.length?<ul className="includedTests">{profile.includedTests.map(test=><li key={test.id}><a href={`/tests/${test.slug}`}>{test.name}</a></li>)}{aarogyamCampPackageIds.has(product.id)?(aarogyamCampReportParameters[profile.id]??[]).map(name=><li key={name}>{name} <small className="calculatedBadge">Calculated</small></li>):null}</ul>:<p>Individual component tests are not separately recorded for this profile.</p>}</div>:null}</article>})}</div></section>:null}
  {includedTestCount>0?<section className="testContentSection"><div className="sectionHeading"><span>{product.includedProfiles?.length?'Additional individual tests':'Included tests'}</span><h2>{product.includedProfiles?.length?`${includedTestCount} individual tests`:product.parameterCount ? `${product.parameterCount} parameters` : `${includedTestCount} tests`}</h2>{product.parameterCount ? <p>{product.includedProfiles?.length?'These tests are included in addition to the profile groups above.':`${includedTestCount} standalone tests${derivedParameterCount > 0 ? ` + ${derivedParameterCount} calculated/derived parameters` : ''}`}</p> : null}</div><ul className="includedTests">{visibleTests.map(test=><li key={test.id}><a href={`/tests/${test.slug}`}>{test.name}</a></li>)}</ul>{includedTestCount>8&&!showAllTests?<button type="button" className="testSecondaryCta" onClick={()=>setShowAllTests(true)}>View all tests</button>:null}</section>:null}
  <section id="lab-partners" className="testContentSection"><div className="sectionHeading"><span>Choose a laboratory</span><h2>Compare eligible lab partners</h2><p>Prices, report times and availability are shown from the catalog records for each eligible partner.</p></div><div className="offerGrid">{product.offers.map(offer=><PartnerOfferCard key={offer.offerId} offer={offer} type={product.type} slug={product.slug} sampleTypes={product.sampleTypes} onSelect={pincode=>add(offer,pincode)}/>)}</div>{alreadyIncluded&&<div className="cartSuccess" role="status">This test is already included in a selected Profile or Package. <a href="/cart">Open Cart</a> to review your selection.</div>}{added&&<div className="cartSuccess" role="status">Added to cart. <a href="/cart">Open Cart</a> when you are ready to continue.</div>}</section>
  {detailsImage && showDetailsImage ? <div className="testDetailsImageModal" style={{position:"fixed",inset:0,zIndex:9999,display:"flex",alignItems:"center",justifyContent:"center",background:"rgba(0,0,0,0.72)",padding:"16px"}} role="dialog" aria-modal="true" aria-label={`${itemNounTitle} details image`}><div className="testDetailsImageModalPanel" style={{position:"relative",maxHeight:"90vh",maxWidth:"90vw",overflow:"auto",background:"#fff",padding:"16px",borderRadius:"12px"}}><button type="button" aria-label={`Close ${itemNoun} details image`} className="testDetailsImageModalClose" onClick={()=>setShowDetailsImage(false)}>Close</button><img src={detailsImage} alt={`${product.name} ${itemNoun} details`} className="testDetailsImageModalImage" style={{display:"block",maxHeight:"90vh",maxWidth:"100%",objectFit:"contain"}} /></div></div> : null}
  <section className="testSafetyNote"><strong>Important</strong><p>{`Preparation and specimen requirements can vary by ${itemNoun} and laboratory. Follow the instructions shown for your selected partner and any advice from your healthcare professional.`}</p></section>
 </main>;
}
