'use client';
import {useEffect,useState,type ChangeEvent} from 'react';

export default function PaymentSettingsPage(){
 const[qr,setQr]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{fetch('/api/admin/payment-qr').then(r=>r.json()).then(d=>{if(d.qrData)setQr(d.qrData)}).catch(()=>{})},[]);
 function pick(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)){setMessage('Please choose a PNG, JPG or WEBP image.');return}const r=new FileReader();r.onload=()=>{setQr(String(r.result||''));setMessage('QR image selected. Click Save Payment QR.')};r.readAsDataURL(f)}
 async function save(){if(!qr)return;setSaving(true);setMessage('');try{const r=await fetch('/api/admin/payment-qr',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({qrData:qr})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save QR.');setMessage('Payment QR saved successfully. It will appear on checkout for Pay at Sample Collection.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save QR.')}finally{setSaving(false)}}
 return <main style={{maxWidth:760,margin:'38px auto',padding:'0 20px',fontFamily:'Arial,sans-serif'}}><div style={{fontSize:12,fontWeight:900,color:'#087f78'}}>TG LABS • PAYMENT SETTINGS</div><h1>Payment QR Code</h1><p style={{color:'#5d6f6b'}}>Upload the UPI/payment QR image that patients can scan when they choose payment at sample collection. Manual QR payments remain pending until staff verifies receipt.</p><div style={{background:'#fff',border:'1px solid #dce9e7',borderRadius:16,padding:24}}><label style={{display:'block',fontWeight:800,marginBottom:10}}>Upload QR image</label><input type="file" accept="image/png,image/jpeg,image/webp" onChange={pick}/>{qr&&<div style={{marginTop:20}}><img src={qr} alt="Payment QR preview" style={{width:260,maxWidth:'100%',border:'1px solid #dce9e7',borderRadius:14,padding:10,background:'#fff'}}/></div>}<button onClick={save} disabled={!qr||saving} style={{marginTop:20,padding:'11px 18px',border:0,borderRadius:10,background:'#087f78',color:'#fff',fontWeight:900,cursor:'pointer'}}>{saving?'Saving…':'Save Payment QR'}</button>{message&&<div style={{marginTop:14,padding:12,borderRadius:10,background:'#f2f8f7'}}>{message}</div>}</div></main>
}
