import { NextRequest, NextResponse } from 'next/server';

const ADMIN_COOKIE='tg_admin_session';
const MANUAL_COOKIE='tg_thyrocare_session';
function b64urlToBytes(value:string){const s=value.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(value.length/4)*4,'=');const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
function b64urlToJson(value:string){return JSON.parse(new TextDecoder().decode(b64urlToBytes(value)))}
function normalizePhone(phone:string){const d=phone.replace(/\D/g,'');return d.length===12&&d.startsWith('91')?d.slice(2):d.slice(-10)}
async function verifyHmac(token:string,secret:string){const parts=token.split('.');if(parts.length!==3||secret.length<32)return null;const [header,payload,signature]=parts;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']);const ok=await crypto.subtle.verify('HMAC',key,b64urlToBytes(signature),new TextEncoder().encode(`${header}.${payload}`));if(!ok)return null;return {header:b64urlToJson(header),payload:b64urlToJson(payload)}}
async function validAdminSession(token:string){const parsed=await verifyHmac(token,process.env.ADMIN_SESSION_SECRET||'');if(!parsed)return false;const h=parsed.header,p=parsed.payload;if(h.alg!=='HS256'||p.iss!=='tg-labs-admin'||p.aud!=='tg-labs-admin-web'||p.role!=='ADMIN')return false;if(typeof p.exp!=='number'||p.exp*1000<Date.now())return false;const allowed=(process.env.ADMIN_PHONE_NUMBERS||'').split(',').map(normalizePhone).filter(Boolean);return !!allowed.length&&allowed.includes(normalizePhone(String(p.phone||'')))}
async function manualIdentity(token:string){const secret=process.env.THYROCARE_SESSION_SECRET||process.env.ADMIN_SESSION_SECRET||'';const parsed=await verifyHmac(token,secret);if(!parsed)return null;const h=parsed.header,p=parsed.payload;if(h.alg!=='HS256'||p.iss!=='tg-labs-thyrocare'||p.aud!=='tg-labs-thyrocare-manual'||!['ADMIN','STAFF'].includes(p.role))return null;if(typeof p.exp!=='number'||p.exp*1000<Date.now())return null;const login=normalizePhone(process.env.THYROCARE_LOGIN_MOBILE||'9701162302');if(normalizePhone(String(p.phone||''))!==login)return null;return {phone:login,role:p.role as 'ADMIN'|'STAFF'}}
function secure(response:NextResponse,admin=false){response.headers.set('X-Content-Type-Options','nosniff');response.headers.set('X-Frame-Options','DENY');response.headers.set('Referrer-Policy','strict-origin-when-cross-origin');response.headers.set('Permissions-Policy','camera=(), microphone=(), geolocation=(), payment=(self)');response.headers.set('Cross-Origin-Opener-Policy','same-origin-allow-popups');response.headers.set('X-Permitted-Cross-Domain-Policies','none');if(process.env.NODE_ENV==='production')response.headers.set('Strict-Transport-Security','max-age=31536000; includeSubDomains');if(admin){response.headers.set('Cache-Control','no-store, max-age=0');response.headers.set('Pragma','no-cache')}return response}

export async function middleware(request:NextRequest){
 const {pathname,search}=request.nextUrl;
 if(pathname==='/admin/login'||pathname==='/api/admin/session'||pathname==='/manual/login'||pathname==='/manual/forgot'||pathname==='/api/manual/session'||pathname==='/api/manual/password/reset')return secure(NextResponse.next(),true);
 const manualPage=pathname==='/manual'||pathname.startsWith('/manual/');const manualApi=pathname.startsWith('/api/admin/thyrocare/');
 if(manualPage||manualApi){try{const token=request.cookies.get(MANUAL_COOKIE)?.value||'';const identity=token?await manualIdentity(token):null;if(!identity)throw new Error('UNAUTHENTICATED');if(pathname.startsWith('/manual/catalog')&&identity.role!=='ADMIN'){const denied=new URL('/manual',request.url);denied.searchParams.set('permission','catalog-admin-only');return secure(NextResponse.redirect(denied),true)}return secure(NextResponse.next(),true)}catch{if(pathname.startsWith('/api/'))return secure(NextResponse.json({error:'Thyrocare dashboard sign-in required.'},{status:401}),true);const login=new URL('/manual/login',request.url);login.searchParams.set('next',`${pathname}${search}`);return secure(NextResponse.redirect(login),true)}}
 const adminSurface=pathname==='/admin'||pathname.startsWith('/admin/')||pathname.startsWith('/api/admin/');if(!adminSurface)return secure(NextResponse.next(),false);
 try{const token=request.cookies.get(ADMIN_COOKIE)?.value||'';if(!token||!(await validAdminSession(token)))throw new Error('UNAUTHENTICATED');return secure(NextResponse.next(),true)}catch{if(pathname.startsWith('/api/'))return secure(NextResponse.json({error:'Admin authentication required.'},{status:401}),true);const login=new URL('/admin/login',request.url);login.searchParams.set('next',`${pathname}${search}`);return secure(NextResponse.redirect(login),true)}
}
export const config={matcher:['/((?!_next/static|_next/image|favicon.ico).*)']};
