'use client';
import { useEffect, useMemo, useState } from 'react';

type Test={id:string;name:string;mrp:number;price:number;diagnosticPartner?:string|null;tat?:string|null;fastingNeeded:boolean;sampleTypes:string[];sampleTypeOther?:string|null;description?:string|null;imageData?:string|null};
type Pack={id:string;name:string;mrp:number;price:number;diagnosticPartner?:string|null;tat?:string|null;fastingNeeded:boolean;sampleTypes:string[];sampleTypeOther?:string|null;description?:string|null;imageData?:string|null;tests:{test:Test}[]};
type Booking={id:string;source:string;mode:string;collectionDate:string;slot:string;status:string;paymentStatus:string;totalAmount:number;patient:{name:string;phone:string};items:{test:Test}[]};
const tabs=['Overview','Bookings','Catalog','Add Test','Add Package','Manual Booking'] as const;
const SAMPLE_TYPES=['Serum','EDTA','Fluoride','Urine','Other'];
const box:React.CSSProperties={background:'#fff',border:'1px solid #dfe9e5',borderRadius:18,padding:20,boxShadow:'0 8px 28px rgba(12,71,61,.06)'};
const input:React.CSSProperties={width:'100%',padding:'12px 14px',border:'1px solid #cddbd6',borderRadius:10,boxSizing:'border-box',fontSize:14};
const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:14};
const btn:React.CSSProperties={background:'#087f6f',color:'#fff',border:0,borderRadius:10,padding:'12px 18px',fontWeight:800,cursor:'pointer'};
const lightBtn:React.CSSProperties={...btn,background:'#e6f1ee',color:'#17463d',padding:'9px 12px'};
const dangerBtn:React.CSSProperties={...btn,background:'#fff0f0',color:'#a72e2e',border:'1px solid #efcaca',padding:'9px 12px'};
async function imageToData(file?:File){if(!file)return '';if(file.size>1500000)throw new Error('Image must be below 1.5 MB.');return await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error('Unable to read image.'));r.readAsDataURL(file);});}
function sampleText(x:{sampleTypes?:string[];sampleTypeOther?:string|null}){const vals=[...(x.sampleTypes||[])];if(vals.includes('Other')&&x.sampleTypeOther)return vals.map(v=>v==='Other'?x.sampleTypeOther!:v).join(', ');return vals.join(', ')||'—';}
function matches(q:string,...parts:(string|number|null|undefined)[]){const s=q.trim().toLowerCase();return !s||parts.some(v=>String(v??'').toLowerCase().includes(s));}

export default function AdminPage(){
 const [tab,setTab]=useState<typeof tabs[number]>('Overview');
 const [tests,setTests]=useState<Test[]>([]); const [packages,setPackages]=useState<Pack[]>([]); const [bookings,setBookings]=useState<Booking[]>([]);
 const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);
 const load=async()=>{const [t,p,b]=await Promise.all([fetch('/api/admin/catalog/tests'),fetch('/api/admin/catalog/packages'),fetch('/api/admin/bookings')]);if(t.ok)setTests((await t.json()).tests);if(p.ok)setPackages((await p.json()).packages);if(b.ok)setBookings((await b.json()).bookings);};
 useEffect(()=>{load()},[]);
 const paid=useMemo(()=>bookings.filter(b=>b.paymentStatus==='PAID'),[bookings]); const revenue=paid.reduce((s,b)=>s+b.totalAmount,0);
 async function send(url:string,method:string,data:any,success:string){setBusy(true);setMsg('');try{const r=await fetch(url,{method,headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to save');setMsg(success);await load();return true}catch(e:any){setMsg(e.message);return false}finally{setBusy(false)}}
 return <main style={{minHeight:'100vh',background:'#f4f8f6',padding:'28px',color:'#12352f',fontFamily:'Arial, sans-serif'}}><div style={{maxWidth:1400,margin:'0 auto'}}>
  <div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'center',marginBottom:18,flexWrap:'wrap'}}><div><div style={{fontSize:12,fontWeight:900,color:'#087f6f',letterSpacing:1.4}}>TG LABS • PHASE 1</div><h1 style={{margin:'6px 0 0',fontSize:34}}>Admin Command Centre</h1><p style={{margin:'8px 0',color:'#60746f'}}>Live bookings, catalog management, pricing, sample requirements and manual staff bookings.</p></div><a href="/" style={{color:'#087f6f',fontWeight:800}}>Open website →</a></div>
  <nav style={{display:'flex',gap:8,overflowX:'auto',marginBottom:20}}>{tabs.map(x=><button key={x} onClick={()=>{setTab(x);setMsg('')}} style={{...btn,background:tab===x?'#087f6f':'#e6f1ee',color:tab===x?'#fff':'#17463d',whiteSpace:'nowrap'}}>{x}</button>)}</nav>
  {msg&&<div style={{...box,marginBottom:16,borderColor:msg.toLowerCase().includes('unable')||msg.toLowerCase().includes('check')?'#f0b8b8':'#9ed6ca'}}>{msg}</div>}
  {tab==='Overview'&&<><section style={{...grid,marginBottom:20}}><Kpi n={bookings.length} label="Total bookings"/><Kpi n={paid.length} label="Paid bookings"/><Kpi n={`₹${revenue.toLocaleString('en-IN')}`} label="Paid value"/><Kpi n={tests.length} label="Tests"/><Kpi n={packages.length} label="Packages"/></section><section style={box}><h2>Latest bookings</h2><BookingTable rows={bookings.slice(0,10)}/></section></>}
  {tab==='Bookings'&&<section style={box}><h2>Booking management</h2><p style={{color:'#667a74'}}>Website and admin-created bookings are read directly from PostgreSQL.</p><BookingTable rows={bookings}/></section>}
  {tab==='Catalog'&&<Catalog tests={tests} packages={packages} busy={busy} onUpdate={async(type,id,data)=>send(`/api/admin/catalog/${type}/${id}`,'PATCH',data,`${type==='tests'?'Test':'Package'} updated successfully.`)} onDelete={async(type,id)=>send(`/api/admin/catalog/${type}/${id}`,'DELETE',null,`${type==='tests'?'Test':'Package'} deleted successfully.`)}/>} 
  {tab==='Add Test'&&<TestForm busy={busy} onSave={async d=>{if(await send('/api/admin/catalog/tests','POST',d,'Diagnostic test added successfully.'))setTab('Catalog')}}/>}
  {tab==='Add Package'&&<PackageForm tests={tests} busy={busy} onSave={async d=>{if(await send('/api/admin/catalog/packages','POST',d,'Health package added successfully.'))setTab('Catalog')}}/>}
  {tab==='Manual Booking'&&<ManualBooking tests={tests} packages={packages} busy={busy} onSave={async d=>{if(await send('/api/admin/bookings','POST',d,'Manual booking created successfully.'))setTab('Bookings')}}/>}
 </div></main>
}
function Kpi({n,label}:{n:any,label:string}){return <article style={box}><div style={{fontSize:30,fontWeight:900,color:'#087f6f'}}>{n}</div><div style={{color:'#687c76',marginTop:6}}>{label}</div></article>}
function BookingTable({rows}:{rows:Booking[]}){return <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:900}}><thead><tr>{['Patient','Source','Tests / Sample','Collection','Payment','Status','Amount'].map(h=><th key={h} style={{textAlign:'left',padding:12,borderBottom:'1px solid #dce7e3',fontSize:12}}>{h}</th>)}</tr></thead><tbody>{rows.map(b=><tr key={b.id}><td style={{padding:12,borderBottom:'1px solid #edf2f0'}}><b>{b.patient.name}</b><br/><small>{b.patient.phone}</small></td><td>{b.source}</td><td>{b.items.map(i=><div key={i.test.id}><b>{i.test.name}</b><br/><small>{sampleText(i.test)}</small></div>)}</td><td>{new Date(b.collectionDate).toLocaleDateString('en-IN')}<br/><small>{b.mode} • {b.slot}</small></td><td><b>{b.paymentStatus}</b></td><td>{b.status}</td><td><b>₹{b.totalAmount}</b></td></tr>)}{!rows.length&&<tr><td colSpan={7} style={{padding:24,textAlign:'center'}}>No bookings yet.</td></tr>}</tbody></table></div>}

function Catalog({tests,packages,busy,onUpdate,onDelete}:{tests:Test[];packages:Pack[];busy:boolean;onUpdate:(type:'tests'|'packages',id:string,data:any)=>Promise<boolean>;onDelete:(type:'tests'|'packages',id:string)=>Promise<boolean>}){
 const [q,setQ]=useState(''); const [editing,setEditing]=useState<{type:'tests'|'packages';item:Test|Pack}|null>(null);
 const filteredTests=tests.filter(t=>matches(q,t.name,t.diagnosticPartner,t.tat,sampleText(t),t.description));
 const filteredPackages=packages.filter(p=>matches(q,p.name,p.diagnosticPartner,p.tat,sampleText(p),p.description,p.tests.map(x=>x.test.name).join(' ')));
 async function remove(type:'tests'|'packages',id:string,name:string){if(!confirm(`Delete ${name}? It will be removed from active catalog and selection lists.`))return;await onDelete(type,id)}
 return <div style={{display:'grid',gap:20}}>
  <section style={box}><div style={{display:'flex',gap:14,justifyContent:'space-between',alignItems:'center',flexWrap:'wrap'}}><div><h2 style={{marginBottom:5}}>Catalog Search</h2><div style={{color:'#687c76',fontSize:13}}>Find a specific test or package by name, partner, TAT, sample type or included test.</div></div><input style={{...input,maxWidth:430}} placeholder="Search test or package..." value={q} onChange={e=>setQ(e.target.value)}/></div></section>
  <section style={box}><h2>Diagnostic Test List</h2><p style={{color:'#687c76'}}>Showing {filteredTests.length} of {tests.length} tests. Edit or delete any active catalog item.</p><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:1250}}><thead><tr>{['Image','Test','MRP','After Discount','Partner','TAT','Fasting','Sample Type','Description','Actions'].map(h=><th key={h} style={{textAlign:'left',padding:10,borderBottom:'1px solid #dce7e3',fontSize:12}}>{h}</th>)}</tr></thead><tbody>{filteredTests.map(t=><tr key={t.id}><td style={{padding:10}}>{t.imageData?<img src={t.imageData} alt="" style={{width:54,height:54,objectFit:'cover',borderRadius:10}}/>:'—'}</td><td><b>{t.name}</b></td><td>₹{t.mrp}</td><td><b>₹{t.price}</b></td><td>{t.diagnosticPartner||'—'}</td><td>{t.tat||'—'}</td><td>{t.fastingNeeded?'Yes':'No'}</td><td>{sampleText(t)}</td><td style={{maxWidth:250}}>{t.description||'—'}</td><td><div style={{display:'flex',gap:7}}><button style={lightBtn} onClick={()=>setEditing({type:'tests',item:t})}>Edit</button><button disabled={busy} style={dangerBtn} onClick={()=>remove('tests',t.id,t.name)}>Delete</button></div></td></tr>)}{!filteredTests.length&&<tr><td colSpan={10} style={{padding:20}}>No matching tests.</td></tr>}</tbody></table></div></section>
  <section style={box}><h2>Health Package List</h2><p style={{color:'#687c76'}}>Showing {filteredPackages.length} of {packages.length} packages.</p><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:1200}}><thead><tr>{['Image','Package','Tests Included','MRP','After Discount','Partner','TAT','Fasting','Sample Type','Actions'].map(h=><th key={h} style={{textAlign:'left',padding:10,borderBottom:'1px solid #dce7e3',fontSize:12}}>{h}</th>)}</tr></thead><tbody>{filteredPackages.map(p=><tr key={p.id}><td style={{padding:10}}>{p.imageData?<img src={p.imageData} alt="" style={{width:54,height:54,objectFit:'cover',borderRadius:10}}/>:'—'}</td><td><b>{p.name}</b></td><td>{p.tests.map(x=>x.test.name).join(', ')}</td><td>₹{p.mrp}</td><td><b>₹{p.price}</b></td><td>{p.diagnosticPartner||'—'}</td><td>{p.tat||'—'}</td><td>{p.fastingNeeded?'Yes':'No'}</td><td>{sampleText(p)}</td><td><div style={{display:'flex',gap:7}}><button style={lightBtn} onClick={()=>setEditing({type:'packages',item:p})}>Edit</button><button disabled={busy} style={dangerBtn} onClick={()=>remove('packages',p.id,p.name)}>Delete</button></div></td></tr>)}{!filteredPackages.length&&<tr><td colSpan={10} style={{padding:20}}>No matching packages.</td></tr>}</tbody></table></div></section>
  {editing&&<EditDialog type={editing.type} item={editing.item} tests={tests} busy={busy} onClose={()=>setEditing(null)} onSave={async data=>{if(await onUpdate(editing.type,editing.item.id,data))setEditing(null)}}/>}
 </div>
}

function TestForm({busy,onSave}:{busy:boolean;onSave:(x:any)=>void}){const [f,setF]=useState<any>({name:'',mrp:'',price:'',diagnosticPartner:'',tat:'',fastingNeeded:false,sampleTypes:[],sampleTypeOther:'',description:'',imageData:''});const set=(k:string,v:any)=>setF({...f,[k]:v});return <section style={box}><h2>Add Diagnostic Test</h2><CatalogFields f={f} setF={setF} imageLabel="Test related image upload"/><button disabled={busy} style={btn} onClick={()=>onSave(f)}>{busy?'Saving…':'Add Test'}</button></section>}
function PackageForm({tests,busy,onSave}:{tests:Test[];busy:boolean;onSave:(x:any)=>void}){const [f,setF]=useState<any>({name:'',mrp:'',price:'',diagnosticPartner:'',tat:'',fastingNeeded:false,sampleTypes:[],sampleTypeOther:'',description:'',imageData:'',testIds:[]});const [search,setSearch]=useState('');const set=(k:string,v:any)=>setF({...f,[k]:v});const shown=tests.filter(t=>matches(search,t.name,t.diagnosticPartner,sampleText(t)));return <section style={box}><h2>Add Health Package</h2><CatalogFields f={f} setF={setF} imageLabel="Package related image upload" nameLabel="Package name" descriptionLabel="Package description"/><h3>Tests included</h3><input style={{...input,maxWidth:520,marginBottom:12}} placeholder="Search a test to include..." value={search} onChange={e=>setSearch(e.target.value)}/><SelectableTests tests={shown} selected={f.testIds} onChange={ids=>set('testIds',ids)}/><button disabled={busy} style={{...btn,marginTop:16}} onClick={()=>onSave(f)}>{busy?'Saving…':'Add Package'}</button></section>}

function CatalogFields({f,setF,imageLabel,nameLabel='Test name',descriptionLabel='Test description'}:{f:any;setF:(x:any)=>void;imageLabel:string;nameLabel?:string;descriptionLabel?:string}){const set=(k:string,v:any)=>setF({...f,[k]:v});return <><div style={grid}><Field label={nameLabel}><input style={input} value={f.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="MRP"><input type="number" style={input} value={f.mrp} onChange={e=>set('mrp',e.target.value)}/></Field><Field label="After Discount"><input type="number" style={input} value={f.price} onChange={e=>set('price',e.target.value)}/></Field><Field label="Diagnostic Partner"><input style={input} placeholder="TG Labs / Thyrocare / Partner" value={f.diagnosticPartner||''} onChange={e=>set('diagnosticPartner',e.target.value)}/></Field><Field label="TAT"><input style={input} placeholder="e.g. 6 hours / Same day" value={f.tat||''} onChange={e=>set('tat',e.target.value)}/></Field><Field label={imageLabel}><input type="file" accept="image/*" style={input} onChange={async e=>{try{const data=await imageToData(e.target.files?.[0]);if(data)set('imageData',data)}catch(err:any){alert(err.message)}}}/></Field></div><label style={{display:'flex',gap:8,margin:'18px 0',alignItems:'center'}}><input type="checkbox" checked={Boolean(f.fastingNeeded)} onChange={e=>set('fastingNeeded',e.target.checked)}/> Fasting needed</label><SampleTypeDialog values={f.sampleTypes||[]} other={f.sampleTypeOther||''} onChange={(values,other)=>setF({...f,sampleTypes:values,sampleTypeOther:other})}/><Field label={descriptionLabel}><textarea style={{...input,minHeight:120}} value={f.description||''} onChange={e=>set('description',e.target.value)}/></Field>{f.imageData&&<img src={f.imageData} alt="Preview" style={{width:120,height:90,objectFit:'cover',borderRadius:12,marginBottom:16}}/>}</>}

function EditDialog({type,item,tests,busy,onClose,onSave}:{type:'tests'|'packages';item:Test|Pack;tests:Test[];busy:boolean;onClose:()=>void;onSave:(x:any)=>void}){
 const pack=type==='packages'?item as Pack:null;
 const [f,setF]=useState<any>({...item,testIds:pack?pack.tests.map(x=>x.test.id):undefined,sampleTypes:[...(item.sampleTypes||[])]});
 const [search,setSearch]=useState('');
 const shown=tests.filter(t=>matches(search,t.name,t.diagnosticPartner,sampleText(t)));
 return <div style={{position:'fixed',inset:0,background:'rgba(10,30,26,.55)',zIndex:1200,overflowY:'auto',padding:22}}><div style={{...box,maxWidth:1000,margin:'20px auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><div><div style={{fontSize:11,fontWeight:900,color:'#087f6f'}}>EDIT {type==='tests'?'TEST':'PACKAGE'}</div><h2 style={{margin:'5px 0 14px'}}>{item.name}</h2></div><button onClick={onClose} style={{border:0,background:'transparent',fontSize:28,cursor:'pointer'}}>×</button></div><CatalogFields f={f} setF={setF} imageLabel={type==='tests'?'Replace test image':'Replace package image'} nameLabel={type==='tests'?'Test name':'Package name'} descriptionLabel={type==='tests'?'Test description':'Package description'}/>{type==='packages'&&<><h3>Tests included</h3><input style={{...input,maxWidth:520,marginBottom:12}} placeholder="Search a test to include..." value={search} onChange={e=>setSearch(e.target.value)}/><SelectableTests tests={shown} selected={f.testIds||[]} onChange={ids=>setF({...f,testIds:ids})}/></>}<div style={{display:'flex',gap:10,justifyContent:'flex-end',marginTop:18}}><button style={lightBtn} onClick={onClose}>Cancel</button><button disabled={busy} style={btn} onClick={()=>onSave(f)}>{busy?'Saving…':'Save Changes'}</button></div></div></div>
}

function SelectableTests({tests,selected,onChange}:{tests:Test[];selected:string[];onChange:(ids:string[])=>void}){return <div style={{...grid,maxHeight:360,overflowY:'auto',padding:2}}>{tests.map(t=><label key={t.id} style={{padding:10,border:'1px solid #dce7e3',borderRadius:10,background:selected.includes(t.id)?'#eff9f6':'#fff'}}><input type="checkbox" checked={selected.includes(t.id)} onChange={e=>onChange(e.target.checked?[...selected,t.id]:selected.filter(x=>x!==t.id))}/> <b>{t.name}</b> • ₹{t.price}<br/><small style={{marginLeft:18}}>Sample: {sampleText(t)} • {t.diagnosticPartner||'No partner'}</small></label>)}{!tests.length&&<div style={{color:'#687c76'}}>No matching tests.</div>}</div>}

function SampleTypeDialog({values,other,onChange}:{values:string[];other:string;onChange:(values:string[],other:string)=>void}){const [open,setOpen]=useState(false);const toggle=(v:string)=>onChange(values.includes(v)?values.filter(x=>x!==v):[...values,v],other);return <div style={{margin:'16px 0 20px'}}><div style={{display:'flex',alignItems:'center',gap:12,flexWrap:'wrap'}}><button type="button" style={lightBtn} onClick={()=>setOpen(true)}>Select Sample Type</button><span style={{fontSize:13,color:'#5f746e'}}>{values.length?sampleText({sampleTypes:values,sampleTypeOther:other}):'No sample type selected'}</span></div>{open&&<div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,background:'rgba(10,30,26,.48)',display:'grid',placeItems:'center',zIndex:1400,padding:20}}><div style={{...box,width:'min(520px,100%)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:11,color:'#087f6f',fontWeight:900,letterSpacing:1}}>SAMPLE REQUIREMENT</div><h3 style={{margin:'6px 0 4px'}}>Choose Sample Type</h3></div><button type="button" onClick={()=>setOpen(false)} style={{border:0,background:'transparent',fontSize:24,cursor:'pointer'}}>×</button></div><p style={{color:'#667a74',fontSize:13}}>Select one or more specimen types required for this test/package.</p><div style={{display:'grid',gap:10}}>{SAMPLE_TYPES.map(v=><label key={v} style={{border:'1px solid #dce7e3',borderRadius:10,padding:12,fontWeight:700}}><input type="checkbox" checked={values.includes(v)} onChange={()=>toggle(v)}/> {v}</label>)}</div>{values.includes('Other')&&<Field label="Others — Specify"><input autoFocus style={input} placeholder="e.g. Plasma, Swab, Stool" value={other} onChange={e=>onChange(values,e.target.value)}/></Field>}<button type="button" style={{...btn,width:'100%'}} onClick={()=>setOpen(false)}>Done</button></div></div>}</div>}

function ManualBooking({tests,packages,busy,onSave}:{tests:Test[];packages:Pack[];busy:boolean;onSave:(x:any)=>void}){
 const today=new Date().toISOString().slice(0,10); const [testSearch,setTestSearch]=useState(''); const [packageSearch,setPackageSearch]=useState('');
 const [f,setF]=useState<any>({name:'',phone:'',mode:'HOME',address:'',date:today,slot:'7:00 AM - 9:00 AM',testIds:[],packageIds:[],paymentStatus:'PENDING',paymentMode:'CASH',adminNotes:''});const set=(k:string,v:any)=>setF({...f,[k]:v});
 const shownTests=tests.filter(t=>matches(testSearch,t.name,t.diagnosticPartner,sampleText(t),t.tat)); const shownPackages=packages.filter(p=>matches(packageSearch,p.name,p.diagnosticPartner,sampleText(p),p.tests.map(x=>x.test.name).join(' ')));
 return <section style={box}><h2>Manual Test Booking</h2><p style={{color:'#657973'}}>Use for walk-ins, phone bookings and bookings taken directly by TG Labs staff.</p><div style={grid}><Field label="Patient name"><input style={input} value={f.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="Mobile number"><input style={input} maxLength={10} value={f.phone} onChange={e=>set('phone',e.target.value.replace(/\D/g,''))}/></Field><Field label="Collection type"><select style={input} value={f.mode} onChange={e=>set('mode',e.target.value)}><option value="HOME">Home Collection</option><option value="CENTRE">Lab Centre</option></select></Field><Field label="Date"><input type="date" style={input} value={f.date} onChange={e=>set('date',e.target.value)}/></Field><Field label="Preferred slot"><select style={input} value={f.slot} onChange={e=>set('slot',e.target.value)}>{['7:00 AM - 9:00 AM','9:00 AM - 11:00 AM','11:00 AM - 1:00 PM','2:00 PM - 4:00 PM','4:00 PM - 6:00 PM'].map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Payment status"><select style={input} value={f.paymentStatus} onChange={e=>set('paymentStatus',e.target.value)}><option value="PENDING">Pending</option><option value="PAID">Paid</option></select></Field><Field label="Payment mode"><select style={input} value={f.paymentMode} onChange={e=>set('paymentMode',e.target.value)}>{['CASH','UPI','CARD','ONLINE','BANK_TRANSFER','OTHER'].map(x=><option key={x}>{x}</option>)}</select></Field></div>{f.mode==='HOME'&&<Field label="Collection address"><textarea style={{...input,minHeight:80}} value={f.address} onChange={e=>set('address',e.target.value)}/></Field>}
 <h3>Select Tests</h3><input style={{...input,maxWidth:560,marginBottom:12}} placeholder="Search specific test by name, partner, sample type or TAT..." value={testSearch} onChange={e=>setTestSearch(e.target.value)}/><SelectableTests tests={shownTests} selected={f.testIds} onChange={ids=>set('testIds',ids)}/>
 <h3>Select Packages</h3><input style={{...input,maxWidth:560,marginBottom:12}} placeholder="Search specific package or included test..." value={packageSearch} onChange={e=>setPackageSearch(e.target.value)}/><div style={{...grid,maxHeight:320,overflowY:'auto'}}>{shownPackages.map(p=><label key={p.id} style={{padding:10,border:'1px solid #dce7e3',borderRadius:10,background:f.packageIds.includes(p.id)?'#eff9f6':'#fff'}}><input type="checkbox" checked={f.packageIds.includes(p.id)} onChange={e=>set('packageIds',e.target.checked?[...f.packageIds,p.id]:f.packageIds.filter((x:string)=>x!==p.id))}/> <b>{p.name}</b> • ₹{p.price}<br/><small style={{marginLeft:18}}>Sample: {sampleText(p)} • Tests: {p.tests.map(x=>x.test.name).join(', ')}</small></label>)}{!shownPackages.length&&<div style={{color:'#687c76'}}>No matching packages.</div>}</div>
 <Field label="Admin notes"><textarea style={{...input,minHeight:90}} value={f.adminNotes} onChange={e=>set('adminNotes',e.target.value)}/></Field><button disabled={busy} style={{...btn,marginTop:12}} onClick={()=>onSave(f)}>{busy?'Creating…':'Create Manual Booking'}</button></section>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:'block',fontWeight:800,marginBottom:14}}><span style={{display:'block',fontSize:13,marginBottom:7}}>{label}</span>{children}</label>}
