'use client';

import { FormEvent,useEffect,useRef,useState } from 'react';
import { ConfirmationResult,RecaptchaVerifier,signInWithPhoneNumber,signOut } from 'firebase/auth';
import { useRouter } from 'next/navigation';
import { auth } from '@/lib/firebase';

export default function AdminLogin(){
 const router=useRouter();const verifier=useRef<RecaptchaVerifier|null>(null);const[phone,setPhone]=useState(''),[otp,setOtp]=useState(''),[confirmation,setConfirmation]=useState<ConfirmationResult|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 function reset(){try{verifier.current?.clear()}catch{}verifier.current=null;const el=document.getElementById('admin-recaptcha');if(el)el.innerHTML=''}
 useEffect(()=>()=>reset(),[]);
 function normalized(){const d=phone.replace(/\D/g,'');if(d.length!==10)throw new Error('Enter a valid 10-digit Indian mobile number.');return `+91${d}`}
 async function sendOtp(e:FormEvent){e.preventDefault();setLoading(true);setMessage('');try{reset();verifier.current=new RecaptchaVerifier(auth,'admin-recaptcha',{size:'invisible'});await verifier.current.render();setConfirmation(await signInWithPhoneNumber(auth,normalized(),verifier.current));setMessage('OTP sent. Enter the 6-digit code received by SMS.')}catch(e){reset();setMessage(e instanceof Error?e.message:'Unable to send OTP.')}finally{setLoading(false)}}
 async function verify(e:FormEvent){e.preventDefault();if(!confirmation)return;setLoading(true);setMessage('');try{const credential=await confirmation.confirm(otp.trim());const token=await credential.user.getIdToken(true);const response=await fetch('/api/admin/session',{method:'POST',headers:{Authorization:`Bearer ${token}`}});const data=await response.json();if(!response.ok){await signOut(auth);throw new Error(data.error||'This mobile number is not authorized for admin access.')}reset();const next=new URLSearchParams(window.location.search).get('next');router.replace(next&&next.startsWith('/')?next:'/admin');router.refresh()}catch(e){setMessage(e instanceof Error?e.message:'Unable to sign in.')}finally{setLoading(false)}}
 return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:20,background:'#f3f8f6',fontFamily:'Arial,sans-serif'}}><section style={{width:'100%',maxWidth:500,background:'#fff',border:'1px solid #dbe7e3',borderRadius:22,padding:28,boxShadow:'0 20px 50px rgba(16,70,60,.08)'}}><div style={{fontSize:12,fontWeight:900,letterSpacing:1,color:'#087f6f'}}>TG LABS • ADMIN SECURITY</div><h1 style={{margin:'8px 0'}}>Admin sign in</h1><p style={{color:'#64748b',lineHeight:1.6}}>Use an authorized administrator mobile number. Access is verified by SMS OTP and a secure server session.</p>{!confirmation?<form onSubmit={sendOtp}><label style={label}>Mobile number<div style={{display:'flex',gap:8,marginTop:7}}><span style={{...input,width:'auto'}}>+91</span><input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,''))} maxLength={10} inputMode="tel" autoComplete="tel" style={{...input,flex:1}} required/></div></label><button style={primary} disabled={loading||phone.length!==10}>{loading?'Sending OTP…':'Send OTP'}</button></form>:<form onSubmit={verify}><label style={label}>6-digit OTP<input value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} maxLength={6} inputMode="numeric" autoComplete="one-time-code" style={{...input,marginTop:7,letterSpacing:5,fontSize:20}} required/></label><button style={primary} disabled={loading||otp.length!==6}>{loading?'Verifying…':'Verify & open Admin'}</button><button type="button" style={secondary} onClick={()=>{reset();setConfirmation(null);setOtp('');setMessage('')}}>Change number</button></form>}<div id="admin-recaptcha"/>{message&&<div style={{marginTop:18,padding:12,borderRadius:12,background:'#fff7ed',color:'#9a4d00'}}>{message}</div>}<p style={{fontSize:12,color:'#64748b',marginTop:22}}>Unauthorized access attempts are blocked. Admin sessions expire automatically.</p></section></main>
}
const label={display:'block',fontWeight:800,marginTop:18} as const,input={boxSizing:'border-box' as const,padding:'12px 13px',border:'1px solid #cad9d4',borderRadius:11,font:'inherit',background:'#fff'} as const,primary={display:'block',marginTop:18,padding:'12px 15px',border:0,borderRadius:11,background:'#087f6f',color:'#fff',fontWeight:900,cursor:'pointer'} as const,secondary={marginTop:12,padding:'10px 13px',border:'1px solid #cad9d4',borderRadius:11,background:'#fff',fontWeight:800,cursor:'pointer'} as const;
