import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const page=fs.readFileSync('app/admin/accounts-logistics/page.tsx','utf8'),api=fs.readFileSync('app/api/admin/accounts-logistics/route.ts','utf8'),chrome=fs.readFileSync('components/DashboardChrome.tsx','utf8');
test('accounts logistics stays inside existing admin shell',()=>{assert.match(chrome,/Accounts & Logistics/);assert.match(chrome,/\/admin\/accounts-logistics/);assert.match(chrome,/\/api\/admin\/session/);});
test('dashboard and reconciliation API are read only',()=>{assert.match(page,/fetch\('\/api\/admin\/accounts-logistics'/);assert.doesNotMatch(page,/method:\s*['"](?:POST|PATCH|PUT|DELETE)/);assert.match(api,/export async function GET/);assert.doesNotMatch(api,/export async function (?:POST|PATCH|PUT|DELETE)/);assert.doesNotMatch(api,/prisma\.[A-Za-z]+?\.(?:create|update|delete|upsert)/);});
test('reconciliation uses stored payment evidence',()=>{assert.match(api,/paymentTransaction\.findMany/);assert.match(api,/razorpayWebhookEvent\.findMany/);assert.match(api,/signatureVerified/);assert.match(page,/Payment reconciliation exceptions/);assert.match(page,/Verified paid transactions/);});
test('financial mutations remain prohibited',()=>{assert.match(page,/never marks a payment paid, refunds a payment, or changes a booking/);assert.match(page,/Partner payables & settlements/);assert.match(page,/Approval, payment and settlement actions are intentionally unavailable here/);assert.match(api,/partnerSettlementTracking:true/);});
test('logistics remains visible and delegates actions',()=>{assert.match(page,/Logistics queue/);assert.match(page,/\/admin\/bookings/);assert.match(page,/\/admin\/operations/);for(const x of ['Payment exceptions','Logistics exceptions','Paid booking value'])assert.match(page,new RegExp(x));});

test('partner payables use recorded values and remain read only',()=>{assert.match(api,/partnerPayable\.findMany/);for(const x of ['Partner payable','Partner paid','Partner outstanding','No partner payable records have been created yet'])assert.match(page,new RegExp(x));assert.doesNotMatch(api,/partnerPayable\.(?:create|update|delete|upsert)/);});
