'use client';
import { useEffect, useMemo, useState } from 'react';
type Booking={id:string;collectionDate:string;slot:string;workflowStatus?:string;status:string;paymentStatus:string;totalAmount:number;mode:string;pincode?:string|null;printedReport?:boolean;patient?:{name?:string};assignedTechnician?:{name?:string}|null};
const card:React.CSSProperties={background:'#fff',border:'1px solid #dfe9e5',borderRadius:16,padding:18,boxShadow:'0 8px 24px rgba(12,71,61,.05)'};
const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12};
const th:React.CSSProperties={textAlign:'left',padding:12,borderBottom:'1px solid #dce7e3',fontSize:12};
const td:React.CSSProperties={padding:12,borderBottom:'1px solid #edf2f0'};
function Metric({label,value}:{label:string;value:string|number}){return <article style={card}><div style={{fontSize:28,fontWeight:900,color:'#087f6f'}}>{value}</div><div style={{color:'#687c76',marginTop:5}}>{label}</div></article>}
export default function AccountsLogisticsPage(){
 const[bookings,setBookings]=useState<Booking[]>([]),[state,setState]=useState<'loading'|'ready'|'unavailable'>('loading');
 useEffect(()=>{fetch('/api/admin/operations',{cache:'no-store'}).then(async r=>{if(!r.ok){setState('unavailable');return}setBookings((await r.json()).bookings||[]);setState('ready')}).catch(()=>setState('unavailable'))},[]);
 const paid=useMemo(()=>bookings.filter(b=>b.paymentStatus==='PAID'),[bookings]),pending=useMemo(()=>bookings.filter(b=>b.paymentStatus!=='PAID'),[bookings]);
 const home=useMemo(()=>bookings.filter(b=>b.mode==='HOME'&&b.workflowStatus!=='REPORT_DELIVERED'),[bookings]),unassigned=useMemo(()=>home.filter(b=>!b.assignedTechnician),[home]);
 const samples=useMemo(()=>bookings.filter(b=>['SAMPLE_COLLECTED','SAMPLE_RECEIVED_AT_LAB','PROCESSING'].includes(b.workflowStatus||'')),[bookings]),printed=useMemo(()=>bookings.filter(b=>b.printedReport&&b.workflowStatus!=='REPORT_DELIVERED'),[bookings]);
 const paidValue=paid.reduce((s,b)=>s+(b.totalAmount||0),0);
 return <main className="accountsLogisticsDashboard" style={{padding:24,color:'#12352f'}}>
  <section style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'end',flexWrap:'wrap',marginBottom:18}}><div><span style={{fontSize:12,fontWeight:900,color:'#087f6f'}}>TG LABS · ADMIN WORKSPACE</span><h1 style={{margin:'6px 0'}}>Accounts & Logistics</h1><p style={{margin:0,color:'#687c76'}}>Read-only operational view of payment status, collections, sample movement and printed-report delivery.</p></div><div style={{display:'flex',gap:10}}><a href="/admin/bookings">Bookings →</a><a href="/admin/operations">Operations →</a></div></section>
  {state==='unavailable'&&<section style={card}>Admin session is required to load live accounts and logistics data.</section>}
  <section style={grid}><Metric label="Paid booking value" value={state==='ready'?('₹'+paidValue.toLocaleString('en-IN')):'—'}/><Metric label="Paid bookings" value={state==='ready'?paid.length:'—'}/><Metric label="Pending / unpaid" value={state==='ready'?pending.length:'—'}/><Metric label="Home collections active" value={state==='ready'?home.length:'—'}/><Metric label="Need technician" value={state==='ready'?unassigned.length:'—'}/><Metric label="Samples in movement" value={state==='ready'?samples.length:'—'}/><Metric label="Printed reports pending" value={state==='ready'?printed.length:'—'}/></section>
  <section style={{...card,marginTop:18}}><h2 style={{marginTop:0}}>Operational queue</h2><p style={{color:'#687c76'}}>Use the existing Operations workspace for technician assignment, workflow updates, report publishing and delivery actions.</p><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:850}}><thead><tr>{['Patient','Collection','Mode','Payment','Amount','Workflow','Technician'].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{bookings.slice(0,30).map(b=><tr key={b.id}><td style={td}><b>{b.patient?.name||'Patient'}</b></td><td style={td}>{new Date(b.collectionDate).toLocaleDateString('en-IN')}<br/><small>{b.slot}</small></td><td style={td}>{b.mode}{b.pincode?<><br/><small>{b.pincode}</small></>:null}</td><td style={td}>{b.paymentStatus}</td><td style={td}><b>₹{(b.totalAmount||0).toLocaleString('en-IN')}</b></td><td style={td}>{b.workflowStatus||b.status}</td><td style={td}>{b.assignedTechnician?.name||'Unassigned'}</td></tr>)}{state==='ready'&&!bookings.length&&<tr><td colSpan={7} style={{padding:24,textAlign:'center'}}>No active operational bookings.</td></tr>}</tbody></table></div></section>
 </main>
}