'use client';
import { useEffect,useState } from 'react';
type Exception={bookingId:string;patient:string;totalAmount:number;paymentStatus:string;paymentMode?:string|null;reasons:string[]};
type Logistics={id:string;patient:string;collectionDate:string;slot:string;mode:string;pincode?:string|null;paymentStatus:string;totalAmount:number;workflowStatus:string;technician?:string|null;printedReport:boolean};
type Payable={id:string;bookingId:string;partnerId:string;partnerName:string;amount:number;currency:string;status:string;sourceReference?:string|null;invoiceNumber?:string|null;invoiceDate?:string|null;approvedAt?:string|null;paidAmount:number;settledAt?:string|null;notes?:string|null};
type Data={summary:{bookings:number;paid:number;paidValue:number;verifiedTransactions:number;paymentExceptions:number;logisticsExceptions:number;partnerPayable:number;partnerPaid:number;partnerOutstanding:number};exceptions:Exception[];logistics:Logistics[];payables:Payable[];partnerSettlementTracking:boolean};
const card:React.CSSProperties={background:'#fff',border:'1px solid #dfe9e5',borderRadius:16,padding:18,boxShadow:'0 8px 24px rgba(12,71,61,.05)'},grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12},td:React.CSSProperties={padding:12,borderBottom:'1px solid #edf2f0'},th:React.CSSProperties={...td,textAlign:'left',fontSize:12};
function Metric({label,value}:{label:string;value:string|number}){return <article style={card}><div style={{fontSize:28,fontWeight:900,color:'#087f6f'}}>{value}</div><div style={{color:'#687c76',marginTop:5}}>{label}</div></article>}
export default function AccountsLogisticsPage(){
 const[data,setData]=useState<Data|null>(null),[state,setState]=useState<'loading'|'ready'|'unavailable'>('loading');
 useEffect(()=>{fetch('/api/admin/accounts-logistics',{cache:'no-store'}).then(async r=>{if(!r.ok){setState('unavailable');return}setData(await r.json());setState('ready')}).catch(()=>setState('unavailable'))},[]);
 const s=data?.summary;
 return <main className="accountsLogisticsDashboard" style={{padding:24,color:'#12352f'}}>
  <section style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'end',flexWrap:'wrap',marginBottom:18}}><div><span style={{fontSize:12,fontWeight:900,color:'#087f6f'}}>TG LABS · ADMIN WORKSPACE</span><h1 style={{margin:'6px 0'}}>Accounts & Logistics</h1><p style={{margin:0,color:'#687c76'}}>Read-only reconciliation and operations exception view from existing booking, payment and webhook evidence.</p></div><div style={{display:'flex',gap:10}}><a href="/admin/bookings">Bookings →</a><a href="/admin/operations">Operations →</a></div></section>
  {state==='unavailable'&&<section style={card}>Admin session is required to load live accounts and logistics data.</section>}
  <section style={grid}><Metric label="Paid booking value" value={s?('₹'+s.paidValue.toLocaleString('en-IN')):'—'}/><Metric label="Paid bookings" value={s?.paid??'—'}/><Metric label="Verified paid transactions" value={s?.verifiedTransactions??'—'}/><Metric label="Payment exceptions" value={s?.paymentExceptions??'—'}/><Metric label="Logistics exceptions" value={s?.logisticsExceptions??'—'}/><Metric label="Partner payable" value={s?('₹'+s.partnerPayable.toLocaleString('en-IN')):'—'}/><Metric label="Partner paid" value={s?('₹'+s.partnerPaid.toLocaleString('en-IN')):'—'}/><Metric label="Partner outstanding" value={s?('₹'+s.partnerOutstanding.toLocaleString('en-IN')):'—'}/></section>
  <section style={{...card,marginTop:18}}><h2 style={{marginTop:0}}>Payment reconciliation exceptions</h2><p style={{color:'#687c76'}}>Exceptions are evidence checks only. This dashboard never marks a payment paid, refunds a payment, or changes a booking.</p>{data?.exceptions.length?<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:760}}><thead><tr>{['Patient','Booking','Payment','Amount','Reason'].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{data.exceptions.map(x=><tr key={x.bookingId}><td style={td}>{x.patient}</td><td style={td}>{x.bookingId}</td><td style={td}>{x.paymentStatus}{x.paymentMode?' · '+x.paymentMode:''}</td><td style={td}>₹{x.totalAmount.toLocaleString('en-IN')}</td><td style={td}>{x.reasons.join('; ')}</td></tr>)}</tbody></table></div>:<p>No payment reconciliation exceptions found in the loaded window.</p>}</section>
  <section style={{...card,marginTop:18}}><h2 style={{marginTop:0}}>Logistics queue</h2><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:850}}><thead><tr>{['Patient','Collection','Mode','Payment','Amount','Workflow','Technician'].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{(data?.logistics||[]).slice(0,50).map(b=><tr key={b.id}><td style={td}>{b.patient}</td><td style={td}>{new Date(b.collectionDate).toLocaleDateString('en-IN')}<br/><small>{b.slot}</small></td><td style={td}>{b.mode}{b.pincode?<><br/><small>{b.pincode}</small></>:null}</td><td style={td}>{b.paymentStatus}</td><td style={td}>₹{b.totalAmount.toLocaleString('en-IN')}</td><td style={td}>{b.workflowStatus}{b.printedReport?' · Printed report':''}</td><td style={td}>{b.technician||'Unassigned'}</td></tr>)}</tbody></table></div></section>
  <section style={{...card,marginTop:18}}><h2 style={{marginTop:0}}>Partner payables & settlements</h2><p style={{color:'#687c76'}}>Read-only recorded values only. Approval, payment and settlement actions are intentionally unavailable here.</p>{data?.payables.length?<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:900}}><thead><tr>{['Partner','Booking','Payable','Paid','Outstanding','Status','Invoice','Settled'].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{data.payables.map(x=><tr key={x.id}><td style={td}>{x.partnerName}</td><td style={td}>{x.bookingId}</td><td style={td}>₹{x.amount.toLocaleString('en-IN')}</td><td style={td}>₹{x.paidAmount.toLocaleString('en-IN')}</td><td style={td}>₹{(x.amount-x.paidAmount).toLocaleString('en-IN')}</td><td style={td}>{x.status}</td><td style={td}>{x.invoiceNumber||'—'}</td><td style={td}>{x.settledAt?new Date(x.settledAt).toLocaleDateString('en-IN'):'—'}</td></tr>)}</tbody></table></div>:<p>No partner payable records have been created yet.</p>}</section>
 </main>
}