'use client';

import { useEffect, useMemo, useState } from 'react';

type Technician={id:string;name:string;phone:string;email?:string|null;employeeCode?:string|null;pincodes:string[];active:boolean;notes?:string|null;bookings:Booking[]};
type Booking={id:string;technicianId?:string|null;technician?:string|null;workflowStatus?:string;collectionDate:string;slot:string;status:string;paymentStatus:string;pincode?:string|null;patient:{name:string;phone:string};items:{test:{name:string}}[]};
const input:React.CSSProperties={width:'100%',padding:'11px 13px',border:'1px solid #cddbd6',borderRadius:10,boxSizing:'border-box'};
const card:React.CSSProperties={background:'#fff',border:'1px solid #dfe9e5',borderRadius:16,padding:16,boxShadow:'0 8px 24px rgba(12,71,61,.05)'};
const btn:React.CSSProperties={border:0,borderRadius:10,padding:'10px 14px',background:'#087f6f',color:'#fff',fontWeight:800,cursor:'pointer'};

export default function TechnicianManagement(){
 const [techs,setTechs]=useState<Technician[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[q,setQ]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[editing,setEditing]=useState<Technician|null>(null);
 const [f,setF]=useState({name:'',phone:'',email:'',employeeCode:'',pincodes:'',active:true,notes:'',loginPin:''});
 const load=async()=>{const[t,b]=await Promise.all([fetch('/api/admin/technicians'),fetch('/api/admin/bookings')]);const tj=await t.json(),bj=await b.json();setTechs(tj.technicians||[]);setBookings(bj.bookings||[])};
 useEffect(()=>{load()},[]);
 const shown=useMemo(()=>techs.filter(t=>(`${t.name} ${t.phone} ${t.email||''} ${t.employeeCode||''} ${t.pincodes.join(' ')}`).toLowerCase().includes(q.toLowerCase())),[techs,q]);
 const today=new Date().toISOString().slice(0,10);
 const activeJobs=(id:string)=>bookings.filter(b=>b.technicianId===id&&!['COMPLETED','CANCELLED'].includes(b.status));
 const todayJobs=(id:string)=>activeJobs(id).filter(b=>new Date(b.collectionDate).toISOString().slice(0,10)===today);
 function reset(){setEditing(null);setF({name:'',phone:'',email:'',employeeCode:'',pincodes:'',active:true,notes:'',loginPin:''})}
 function edit(t:Technician){setEditing(t);setF({name:t.name,phone:t.phone,email:t.email||'',employeeCode:t.employeeCode||'',pincodes:t.pincodes.join(', '),active:t.active,notes:t.notes||'',loginPin:''});window.scrollTo({top:0,behavior:'smooth'})}
 async function save(){setBusy(true);setMsg('');try{if(!editing&&!/^[0-9]{4,6}$/.test(f.loginPin))throw new Error('Set a 4–6 digit technician login PIN.');const data={...f,pincodes:f.pincodes.split(',').map(x=>x.trim()).filter(Boolean)};const r=await fetch(editing?`/api/admin/technicians/${editing.id}`:'/api/admin/technicians',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to save technician');setMsg(editing?'Technician updated.':'Technician added.');reset();await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function deactivate(id:string){if(!confirm('Deactivate this technician? Existing booking history will remain.'))return;setBusy(true);const r=await fetch(`/api/admin/technicians/${id}`,{method:'DELETE'});if(!r.ok)setMsg((await r.json()).error||'Unable to deactivate technician');else{setMsg('Technician deactivated.');await load()}setBusy(false)}
 async function assign(bookingId:string,technicianId:string){setBusy(true);setMsg('');const r=await fetch(`/api/admin/bookings/${bookingId}/technician`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({technicianId:technicianId||null})});const j=await r.json();if(!r.ok)setMsg(j.error||'Unable to assign technician');else{setMsg(technicianId?'Technician assigned successfully.':'Technician removed from booking.');await load()}setBusy(false)}
 return <main style={{minHeight:'100vh',background:'#f4f8f6',padding:28,fontFamily:'Arial,sans-serif',color:'#12352f'}}><div style={{maxWidth:1450,margin:'0 auto'}}>
  <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontSize:12,fontWeight:900,color:'#087f6f'}}>TG LABS • PHASE 2.3</div><h1 style={{marginBottom:4}}>Technician Management</h1><p style={{marginTop:0,color:'#657973'}}>Create technicians, set portal PINs, define service pincodes, assign bookings and monitor workload/history.</p></div><div style={{display:'flex',gap:14}}><a href="/technician/login" style={{color:'#087f6f',fontWeight:800}}>Technician Portal</a><a href="/admin/bookings" style={{color:'#087f6f',fontWeight:800}}>Booking Management</a><a href="/admin" style={{color:'#087f6f',fontWeight:800}}>Admin Dashboard</a></div></div>
  {msg&&<div style={{...card,margin:'16px 0'}}>{msg}</div>}
  <section style={{...card,marginTop:18}}><h2>{editing?'Edit Technician':'Add Technician'}</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12}}><label>Name<input style={input} value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Mobile Number<input style={input} maxLength={10} value={f.phone} onChange={e=>setF({...f,phone:e.target.value.replace(/\D/g,'').slice(0,10)})}/></label><label>Email ID<input type="email" style={input} value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label><label>Employee Code<input style={input} value={f.employeeCode} onChange={e=>setF({...f,employeeCode:e.target.value})} placeholder="e.g. TECH-001"/></label><label>Login PIN {editing&&<small>(leave blank to keep)</small>}<input type="password" inputMode="numeric" style={input} maxLength={6} value={f.loginPin} onChange={e=>setF({...f,loginPin:e.target.value.replace(/\D/g,'').slice(0,6)})} placeholder="4–6 digits"/></label><label>Service Pincodes<input style={input} value={f.pincodes} onChange={e=>setF({...f,pincodes:e.target.value.replace(/[^0-9, ]/g,'')})} placeholder="500061, 500007"/></label><label>Status<select style={input} value={f.active?'ACTIVE':'INACTIVE'} onChange={e=>setF({...f,active:e.target.value==='ACTIVE'})}><option>ACTIVE</option><option>INACTIVE</option></select></label></div><label style={{display:'block',marginTop:12}}>Notes<textarea style={{...input,minHeight:80}} value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label><div style={{display:'flex',gap:10,marginTop:14}}><button disabled={busy} style={btn} onClick={save}>{busy?'Saving…':editing?'Save Changes':'Add Technician'}</button>{editing&&<button style={{...btn,background:'#e7f1ee',color:'#17463d'}} onClick={reset}>Cancel</button>}</div></section>
  <section style={{...card,marginTop:18}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap',alignItems:'center'}}><div><h2 style={{marginBottom:4}}>Technician Directory</h2><small>{techs.filter(t=>t.active).length} active technicians</small></div><input style={{...input,maxWidth:420}} placeholder="Search technician, phone, code or pincode..." value={q} onChange={e=>setQ(e.target.value)}/></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:12,marginTop:15}}>{shown.map(t=><article key={t.id} style={{border:'1px solid #e0eae6',borderRadius:14,padding:14,opacity:t.active?1:.62}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><b style={{fontSize:18}}>{t.name}</b><div style={{fontSize:12,color:'#657973'}}>{t.employeeCode||'No employee code'} • {t.active?'ACTIVE':'INACTIVE'}</div></div><div style={{fontWeight:900,color:'#087f6f'}}>{activeJobs(t.id).length} jobs</div></div><div style={{marginTop:10}}>{t.phone}{t.email?<><br/>{t.email}</>:null}</div><div style={{marginTop:8,fontSize:13}}><b>Service pincodes:</b> {t.pincodes.join(', ')||'All/Not specified'}</div><div style={{marginTop:8,fontSize:13}}><b>Today:</b> {todayJobs(t.id).length} assigned</div><div style={{display:'flex',gap:8,marginTop:12}}><button style={{...btn,padding:'8px 11px'}} onClick={()=>edit(t)}>Edit / Reset PIN</button>{t.active&&<button disabled={busy} style={{...btn,padding:'8px 11px',background:'#fff0f0',color:'#a72e2e',border:'1px solid #efcaca'}} onClick={()=>deactivate(t.id)}>Deactivate</button>}</div></article>)}{!shown.length&&<div>No matching technicians.</div>}</div></section>
  <section style={{...card,marginTop:18}}><h2>Booking Assignment & Workload</h2><p style={{color:'#657973'}}>Assign an active technician. For home collections, use the patient pincode to choose the most suitable technician.</p><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:1100}}><thead><tr>{['Patient','Tests','Date / Slot','Pincode','Workflow','Current Technician','Assign Technician'].map(h=><th key={h} style={{textAlign:'left',padding:10,borderBottom:'1px solid #dce7e3',fontSize:12}}>{h}</th>)}</tr></thead><tbody>{bookings.filter(b=>!['COMPLETED','CANCELLED'].includes(b.status)).map(b=><tr key={b.id}><td style={{padding:10,borderBottom:'1px solid #edf2f0'}}><b>{b.patient.name}</b><br/><small>{b.patient.phone}</small></td><td>{b.items.map(i=>i.test.name).join(', ')}</td><td>{new Date(b.collectionDate).toLocaleDateString('en-IN')}<br/><small>{b.slot}</small></td><td>{b.pincode||'—'}</td><td>{b.workflowStatus||'BOOKING_CREATED'}</td><td>{b.technician||'Unassigned'}</td><td><select disabled={busy} style={{...input,minWidth:220}} value={b.technicianId||''} onChange={e=>assign(b.id,e.target.value)}><option value="">Unassigned</option>{techs.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.name}{b.pincode&&t.pincodes.includes(b.pincode)?' • PIN MATCH':''}</option>)}</select></td></tr>)}{!bookings.length&&<tr><td colSpan={7} style={{padding:20,textAlign:'center'}}>No bookings found.</td></tr>}</tbody></table></div></section>
 </div></main>
}
