import type { Metadata } from 'next';
import BrandLogo from '@/components/BrandLogo';

const url='https://www.tglabs.in/thyrocare-sithaphalmandi';
export const metadata:Metadata={
 title:'Thyrocare Sithaphalmandi, Secunderabad | TG Labs',
 description:'Find Thyrocare diagnostic testing and home sample collection options for Sithaphalmandi and nearby Secunderabad through TG Labs. Check live tests, packages, prices and booking eligibility.',
 alternates:{canonical:url},robots:{index:true,follow:true},
 openGraph:{title:'Thyrocare Sithaphalmandi, Secunderabad | TG Labs',description:'Local Thyrocare testing access, home sample collection and TG Labs booking support for Sithaphalmandi, Secunderabad.',url,type:'website'}
};
const breadcrumbs={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:'https://www.tglabs.in'},{'@type':'ListItem',position:2,name:'Thyrocare Sithaphalmandi',item:url}]};
const localBusiness={'@context':'https://schema.org','@type':'LocalBusiness',name:'Thyrocare Diagnostic Centre - Sithaphalmandi',url,telephone:'+91-97011-62302',address:{'@type':'PostalAddress',streetAddress:'H. Sithaphalmandi 11-1-163, Opp. State Bank of India Mylargadda, Main Road',addressLocality:'Secunderabad',addressRegion:'Telangana',postalCode:'500061',addressCountry:'IN'},areaServed:['Sithaphalmandi','Secunderabad']};
export default function Page(){return <main style={{minHeight:'100vh',background:'#f7faf9',color:'#163b34',fontFamily:'Arial,sans-serif'}}>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbs)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(localBusiness)}}/>
<header style={{background:'#fff',borderBottom:'1px solid #dbe8e3'}}><div style={{maxWidth:1180,margin:'0 auto',padding:'18px 22px',display:'flex',justifyContent:'space-between',gap:16,flexWrap:'wrap'}}><a href="/" aria-label="TG Labs home" style={{width:150}}><BrandLogo/></a><nav style={{display:'flex',gap:18,flexWrap:'wrap'}}><a href="/">Home</a><a href="/#catalog">Tests & Packages</a><a href="/home-blood-test-hyderabad">Home Collection</a><a href="/compare/labs">Partner Labs</a></nav></div></header>
<section style={{maxWidth:1180,margin:'0 auto',padding:'18px 22px 0'}}><nav aria-label="Breadcrumb"><a href="/">Home</a> / <span>Thyrocare Sithaphalmandi</span></nav></section>
<section style={{maxWidth:1180,margin:'0 auto',padding:'42px 22px 28px'}}><span style={{fontSize:12,fontWeight:900,letterSpacing:1.3,color:'#087f6f'}}>TG LABS · LOCAL DIAGNOSTIC BOOKING</span><h1 style={{fontSize:'clamp(34px,5vw,56px)',lineHeight:1.05}}>Thyrocare diagnostic testing in Sithaphalmandi, Secunderabad.</h1><p style={{maxWidth:860,fontSize:18,lineHeight:1.7,color:'#536b65'}}>TG Labs helps patients discover and book eligible Thyrocare tests and health packages for the Sithaphalmandi area. Check the live catalog for current patient price, test or package details, fasting information, sample requirements and home collection eligibility before booking.</p><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><a href="/?partner=thyrocare#catalog" style={{background:'#087f6f',color:'#fff',padding:'13px 18px',borderRadius:10,fontWeight:800}}>View Thyrocare tests & packages</a><a href="tel:+919701162302" style={{background:'#fff',color:'#087f6f',padding:'13px 18px',borderRadius:10,fontWeight:800}}>Call 97011 62302</a></div></section>
<section style={{maxWidth:1180,margin:'0 auto',padding:'8px 22px 36px',display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:16}}><article style={{background:'#fff',border:'1px solid #dce9e4',borderRadius:18,padding:22}}><h2>Visit the Sithaphalmandi centre</h2><p style={{lineHeight:1.65}}>H. Sithaphalmandi 11-1-163, opposite State Bank of India Mylargadda, Main Road, Seethaphalmandi, Secunderabad, Telangana 500061.</p></article><article style={{background:'#fff',border:'1px solid #dce9e4',borderRadius:18,padding:22}}><h2>Home sample collection</h2><p style={{lineHeight:1.65}}>Home sample collection may be available for eligible tests and packages. Availability depends on pincode, partner eligibility, operational coverage and the selected collection slot.</p></article><article style={{background:'#fff',border:'1px solid #dce9e4',borderRadius:18,padding:22}}><h2>Call or WhatsApp</h2><p style={{lineHeight:1.65}}>For local booking assistance, call <a href="tel:+919701162302">+91 97011 62302</a>. WhatsApp enquiries can use the centre's WhatsApp contact shown on its Google Business Profile.</p></article></section>
<section style={{maxWidth:1180,margin:'0 auto 54px',padding:'0 22px'}}><div style={{background:'#e8f5f1',borderRadius:18,padding:24,lineHeight:1.65}}><h2>Book through TG Labs</h2><p>TG Labs is a multi-lab diagnostic booking platform. Thyrocare is one of the laboratory options presented where the relevant offer is currently displayable and eligible. TG Labs does not represent this page as Thyrocare's corporate website. Prices, package contents, turnaround times and availability can change; confirm the current details in the live booking flow.</p><div style={{display:'flex',gap:18,flexWrap:'wrap'}}><a href="/?partner=thyrocare#catalog">Search Thyrocare options →</a><a href="/home-blood-test-hyderabad">Home blood test options →</a><a href="/full-body-checkup-hyderabad">Health checkup options →</a></div></div></section>
</main>}