import { Suspense } from 'react';
import BrandLogo from '@/components/BrandLogo';
import CatalogFilters from '@/components/catalog/CatalogFilters';
import CatalogBrowser from '@/components/catalog/CatalogBrowser';
import '@/app/homepage-reference.css';
import '@/app/homepage-reference-exact.css';
import '@/app/homepage-reference-media.css';

const packages = [
  { title: 'Aarogyam Pro', subtitle: 'Full Body Checkup', tests: '70+ Tests', fasting: 'Fasting Required', image: 'https://images.pexels.com/photos/7904471/pexels-photo-7904471.jpeg?auto=compress&cs=tinysrgb&w=260', alt: 'Doctor representing full body health check', query: 'full body' },
  { title: 'Executive Health Check', subtitle: 'For Men', tests: '80+ Tests', fasting: 'Fasting Required', image: 'https://images.pexels.com/photos/27298085/pexels-photo-27298085.jpeg?auto=compress&cs=tinysrgb&w=260', alt: 'Male doctor representing men health check', query: 'men health' },
  { title: 'Executive Health Check', subtitle: 'For Women', tests: '80+ Tests', fasting: 'Fasting Required', image: 'https://images.pexels.com/photos/5998467/pexels-photo-5998467.jpeg?auto=compress&cs=tinysrgb&w=260', alt: 'Female doctor representing women health check', query: 'women health' },
  { title: 'Diabetes Care Package', subtitle: 'Preventive Screening', tests: '50+ Tests', fasting: 'Fasting Required', image: 'https://images.pexels.com/photos/33200678/pexels-photo-33200678.jpeg?auto=compress&cs=tinysrgb&w=260', alt: 'Blood glucose meter for diabetes screening', query: 'diabetes' },
  { title: 'Thyroid Profile', subtitle: 'T3, T4, TSH', tests: '3 Tests', fasting: 'Fasting Not Required', image: 'https://images.pexels.com/photos/6749781/pexels-photo-6749781.jpeg?auto=compress&cs=tinysrgb&w=260', alt: 'Healthcare professional representing thyroid testing', query: 'thyroid' },
  { title: 'Vitamin D (25-OH)', subtitle: 'Vitamin Screening', tests: '1 Test', fasting: 'Fasting Not Required', image: 'https://images.pexels.com/photos/29183566/pexels-photo-29183566.jpeg?auto=compress&cs=tinysrgb&w=260', alt: 'Healthy sunlight and wellness for vitamin screening', query: 'vitamin d' },
];

export default function Home() {
  return (
    <main className="refHome refHomeExact">
      <header className="refHeader"><div className="refWrap refNav"><a href="/" className="refBrand" aria-label="TG Labs home"><BrandLogo priority /></a><nav className="refLinks" aria-label="Primary navigation"><a href="/">Home</a><a href="#catalog">Tests</a><a href="/packages/full-body-checkup">Packages</a><a href="/compare/labs">Partners</a><a href="#services">Health Blog</a><a href="/contact-us">About</a></nav><div className="refNavMeta"><div className="refMetaBox"><span>⌖</span><div><b>Hyderabad</b><small>Change</small></div></div><div className="refMetaBox"><span>☎</span><div><b>+91 98765 43210</b><small>Call us</small></div></div><a className="refLogin" href="/auth">Login</a><a className="refBook" href="#catalog">Book Now</a></div></div></header>
      <section className="refHero refHeroExact"><div className="refWrap refHeroGrid"><div className="refHeroCopy"><span className="refTrustBadge">✹ NABL TRUSTED LABS</span><h1>Your Health<span>Our Priority</span></h1><p>Book diagnostic tests from trusted NABL labs.<br/>Home sample collection. Affordable prices.<br/>Accurate reports. A healthier tomorrow.</p><form className="refSearch" action="/" method="get"><span>⌕</span><input name="q" type="search" placeholder="Search for tests, packages or health conditions..." aria-label="Search tests and packages" /><button type="submit">Search Tests</button></form><div className="refPopular">Popular searches: <a href="/?q=CBC#catalog">CBC</a><a href="/?q=Thyroid#catalog">Thyroid Profile</a><a href="/?q=Diabetes#catalog">Diabetes</a><a href="/?q=Vitamin%20D#catalog">Vitamin D</a><a href="/?q=Lipid#catalog">Lipid Profile</a><a href="/?q=full%20body#catalog">Full Body Checkup</a></div></div><div className="refFamilyVisual refFamilyPhoto"><img src="https://images.pexels.com/photos/29925535/pexels-photo-29925535.jpeg?auto=compress&cs=tinysrgb&w=900" alt="Smiling family representing preventive diagnostic care" loading="eager" /></div><aside className="refHeroNotes"><div className="refHeroNote"><span>⌂</span><b>Home Sample<br/>Collection</b></div><div className="refHeroNote"><span>♢</span><b>NABL Trusted<br/>Labs</b></div><div className="refHeroNote"><span>₹</span><b>Pay at<br/>Collection</b></div><div className="refHeroNote"><span>▤</span><b>View & Download<br/>Reports</b></div><div className="refHeroScribble">Healthy<br/>Families<br/>Tomorrows</div></aside></div></section>
      <section className="refPartnerStrip"><div className="refWrap refPartnerGrid"><div className="refPartnerItem ownLab"><BrandLogo/><span>TG Labs<br/><small>Our Own Lab</small></span></div><div className="refPartnerItem"><img src="/partners/thyrocare.svg" alt="Thyrocare" /></div><div className="refPartnerItem"><img src="/partners/sagepath-labs.svg" alt="Sagepath Diagnostics" /></div><div className="refPartnerItem"><img src="/partners/dr-lal-pathlabs.svg" alt="Dr Lal PathLabs" /></div><div className="refPartnerItem"><span>✹</span><span>NABL<br/><small>Accredited Labs</small></span></div><div className="refPartnerItem"><span>♧</span><span>Affordable<br/><small>Pricing</small></span></div><div className="refPartnerItem"><span>◉</span><span>Dedicated<br/><small>Support</small></span></div></div></section>
      <section className="refPackages refPackagesExact"><div className="refWrap"><div className="refSectionHead"><h2>Popular Health Packages</h2><a href="#catalog">View All Packages →</a></div><div className="refPackageGrid">{packages.map((pkg,index)=><article className="refPackageCard" key={`${pkg.title}-${pkg.subtitle}`}><div className="refPackageTitleRow"><h3>{pkg.title}<br/><small>{pkg.subtitle}</small></h3><div className="refPackageMedia"><img src={pkg.image} alt={pkg.alt} loading="lazy" /></div></div><div className="refPackageMeta"><span>▤ {pkg.tests}</span><span>♨ {pkg.fasting}</span></div><div className="refPackagePrice"><div><small>Compare live partner prices</small><strong>Live Price</strong><em>{index<3?'Popular':'Recommended'}</em></div><a href={`/?q=${encodeURIComponent(pkg.query)}#catalog`}>Book Now</a></div></article>)}</div></div></section>
      <section id="services" className="refServiceStrip"><div className="refWrap refServiceGrid"><div className="refServiceItem"><span>🚚</span><div><b>Home Sample Collection</b><small>Safe. Convenient. Reliable.</small></div></div><div className="refServiceItem"><span>▤</span><div><b>Accurate Reports</b><small>Digital reports with lab validation.</small></div></div><div className="refServiceItem"><span>♢</span><div><b>Trusted & Secure</b><small>Your data is safe with us.</small></div></div><div className="refServiceItem"><span>♧</span><div><b>Customer Support</b><small>We're here to help.</small></div></div></div></section>
      <section className="refCta"><div className="refWrap refCtaInner"><div className="refLeaf">🍃</div><div className="refCtaCopy"><h2>Book. Test. Stay Healthy.</h2><p>Because prevention is better than cure.</p></div><div className="refCtaTrust"><span>▣ Easy Booking</span><span>♢ Trusted Labs</span><span>₹ Great Prices</span><span>♡ Better Health</span></div><a href="#catalog">Book a Test Now →</a></div></section>
      <section id="catalog" className="refLiveCatalog"><div className="refWrap"><div className="refSectionHead"><div><h2>Search Tests & Packages</h2><div className="refCatalogIntro">Browse the live TG Labs catalog, compare available partner options and check serviceability before booking.</div></div></div><Suspense fallback={<div className="catalogState">Loading catalog…</div>}><CatalogFilters/><CatalogBrowser compact compactCount={3}/></Suspense></div></section>
      <footer className="refFooter refFooterPremium"><div className="refWrap refFooterTop"><div className="refFooterBrand"><BrandLogo variant="footer"/><p>Trusted diagnostic discovery, home sample collection and secure digital reports through TG Labs and eligible partner laboratories.</p><div className="refFooterTrust"><span>✹ NABL-focused labs</span><span>⌂ Home collection</span><span>▤ Digital reports</span></div></div><div className="refFooterCol"><b>Explore</b><a href="#catalog">Tests & Packages</a><a href="/compare/labs">Partner Labs</a><a href="/packages/full-body-checkup">Health Packages</a><a href="#services">Home Collection</a></div><div className="refFooterCol"><b>Patients</b><a href="/auth">Patient Login</a><a href="/cart">My Cart</a><a href="#catalog">Book a Test</a><a href="/patient">My Dashboard</a></div><div className="refFooterCol"><b>Support</b><a href="/contact-us">Contact Us</a><a href="/privacy-policy">Privacy Policy</a><a href="/terms">Terms</a><a href="tel:+919876543210">+91 98765 43210</a></div></div><div className="refWrap refFooterContact"><div><span>⌖</span><b>Hyderabad</b><small>Home sample collection</small></div><div><span>☎</span><b>Customer Support</b><small>Call for booking assistance</small></div><div><span>♢</span><b>Trusted Partners</b><small>TG Labs + eligible partner labs</small></div><a href="#catalog">Book a Test →</a></div><div className="refFooterBottom"><div className="refWrap"><span>© 2026 TG Labs. All rights reserved.</span><span>Book. Test. Stay Healthy.</span></div></div></footer>
      <a className="refFloating" href="#catalog">Book a Test</a>
    </main>
  );
}
