'use client';

import { useEffect, useState } from 'react';

type Partner = {
  id:string; slug:string; name:string; active:boolean; bookingEnabled:boolean; operationalEnabled:boolean; displayEnabled:boolean;
  accreditationDisplay:string|null; accreditationReference:string|null; accreditationVerifiedAt:string|null;
  orderHandoffMethod:string|null; reportIntakeMethod:string|null; updatedAt:string;
  _count:{offers:number;packageOffers:number;serviceability:number};
};

export default function PartnerCatalogAdminPage(){
 const [partners,setPartners]=useState<Partner[]>([]),[selected,setSelected]=useState<Partner|null>(null),[message,setMessage]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const res=await fetch('/api/admin/partner-catalog',{cache:'no-store'});const data=await res.json();if(res.ok){setPartners(data.partners);setSelected((current)=>data.partners.find((p:Partner)=>p.id===current?.id)||data.partners[0]||null)}else setMessage(data.error||'Unable to load partners.');setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setMessage('Saving…');const fd=new FormData(e.currentTarget);const payload={name:String(fd.get('name')||''),accreditationDisplay:String(fd.get('accreditationDisplay')||'')||null,accreditationReference:String(fd.get('accreditationReference')||'')||null,accreditationVerifiedAt:String(fd.get('accreditationVerifiedAt')||'')?new Date(String(fd.get('accreditationVerifiedAt'))).toISOString():null,orderHandoffMethod:String(fd.get('orderHandoffMethod')||'')||null,reportIntakeMethod:String(fd.get('reportIntakeMethod')||'')||null};const res=await fetch(`/api/admin/partner-catalog/${selected.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok){setMessage(data.error||'Update failed.');return}setMessage('Partner metadata saved and audited. Activation state was not changed.');await load()}
 return <main style={{maxWidth:1180,margin:'0 auto',padding:'28px 18px 60px',fontFamily:'Arial,sans-serif'}}><header style={{marginBottom:22}}><p style={{fontWeight:900,color:'#16705d'}}>PHASE 2C-4 • ADMIN METADATA ONLY</p><h1>Partner catalog administration</h1><p>Maintain descriptive partner metadata. Booking, operations, display activation and serviceability are locked in this interface and API.</p></header>{message&&<div role="status" style={{padding:12,border:'1px solid #cfe1dc',borderRadius:10,marginBottom:18}}>{message}</div>}<div style={{display:'grid',gridTemplateColumns:'minmax(250px,340px) minmax(0,1fr)',gap:22}}><section><h2>Partners</h2>{loading?<p>Loading…</p>:partners.map(p=><button key={p.id} onClick={()=>setSelected(p)} style={{display:'block',width:'100%',textAlign:'left',padding:14,marginBottom:10,borderRadius:12,border:p.id===selected?.id?'2px solid #16705d':'1px solid #d8e5e1',background:'#fff',cursor:'pointer'}}><strong>{p.name}</strong><br/><small>{p.slug}</small><br/><small>{p._count.offers} tests • {p._count.packageOffers} packages • {p._count.serviceability} serviceability rows</small></button>)}</section><section>{selected&&<><div style={{padding:16,borderRadius:12,background:'#f3f8f6',marginBottom:18}}><strong>Activation safety lock</strong><p style={{marginBottom:0}}>Active: {String(selected.active)} • Booking: {String(selected.bookingEnabled)} • Operations: {String(selected.operationalEnabled)} • Display: {String(selected.displayEnabled)}</p><small>Read-only. Phase 2C-4 cannot change these flags or serviceability.</small></div><form key={selected.id} onSubmit={save} style={{display:'grid',gap:14}}><label>Name<input name="name" defaultValue={selected.name} required style={input}/></label><label>Accreditation display<input name="accreditationDisplay" defaultValue={selected.accreditationDisplay||''} style={input}/></label><label>Accreditation reference<input name="accreditationReference" defaultValue={selected.accreditationReference||''} style={input}/></label><label>Accreditation verified at<input type="datetime-local" name="accreditationVerifiedAt" defaultValue={selected.accreditationVerifiedAt?selected.accreditationVerifiedAt.slice(0,16):''} style={input}/></label><label>Order handoff method<textarea name="orderHandoffMethod" defaultValue={selected.orderHandoffMethod||''} style={input}/></label><label>Report intake method<textarea name="reportIntakeMethod" defaultValue={selected.reportIntakeMethod||''} style={input}/></label><button type="submit" style={{padding:12,border:0,borderRadius:10,background:'#102f29',color:'#fff',fontWeight:900,cursor:'pointer'}}>Save metadata</button></form></>}</section></div></main>
}
const input={display:'block',width:'100%',boxSizing:'border-box' as const,marginTop:6,padding:10,border:'1px solid #bfcfca',borderRadius:8,font:'inherit'};
