export type HealthArticle={slug:string;title:string;description:string;summary:string;readingTime:string;updated:string;searchQuery:string;sections:{heading:string;body:string[]}[]};

export const healthArticles:HealthArticle[]=[
 {slug:'cbc-test-explained',title:'CBC Test Explained: What a Complete Blood Count Measures',description:'A patient-friendly overview of the CBC blood test, the cell groups it measures, common reasons it may be ordered, and how to prepare.',summary:'Understand the main parts of a Complete Blood Count (CBC) and what to expect when your doctor recommends this common blood test.',readingTime:'4 min read',updated:'2026-09-14',searchQuery:'CBC',sections:[
  {heading:'What is a CBC test?',body:['A Complete Blood Count, or CBC, is a blood test that measures several types of cells circulating in your blood. It commonly reports red blood cells, white blood cells, platelets, haemoglobin and related indices.','Doctors may use a CBC as part of a routine health assessment or when evaluating symptoms such as tiredness, fever, weakness, bruising or other concerns. The test itself does not establish a diagnosis on its own.']},
  {heading:'What does a CBC measure?',body:['Red-cell measurements help describe the number and characteristics of cells that carry oxygen. White-cell measurements describe cells involved in immune responses. Platelets are involved in normal blood clotting.','Laboratories may report additional indices alongside these counts. Reference intervals can vary by laboratory, age, sex and clinical context, so results should be interpreted with your clinician.']},
  {heading:'Preparation and sample',body:['A CBC usually uses a small venous blood sample. Fasting is not generally required for a CBC alone, although another test ordered at the same time may have different preparation requirements. Always follow the instructions attached to your actual booking or provided by your clinician.']}
 ]},
 {slug:'thyroid-profile-t3-t4-tsh',title:'Thyroid Profile: Understanding T3, T4 and TSH Tests',description:'Learn what TSH, T3 and T4 blood tests measure and why doctors may request a thyroid profile.',summary:'A simple guide to TSH, T3 and T4 testing, including why thyroid profiles are ordered and how results are interpreted in context.',readingTime:'4 min read',updated:'2026-09-14',searchQuery:'Thyroid',sections:[
  {heading:'What is a thyroid profile?',body:['A thyroid profile is a group of blood tests used to assess thyroid function. Depending on the panel, it may include thyroid-stimulating hormone (TSH), thyroxine (T4), triiodothyronine (T3), or free forms of T3 and T4.','The thyroid gland produces hormones that influence metabolism, temperature regulation, heart rate and many other body functions.']},
  {heading:'Why are TSH, T3 and T4 measured?',body:['TSH is produced by the pituitary gland and helps regulate thyroid hormone production. T4 is the main hormone produced by the thyroid, while T3 is a more active thyroid hormone in body tissues.','Clinicians consider these values together with symptoms, medicines, pregnancy status and other medical factors. A single result should not be interpreted in isolation.']},
  {heading:'Preparing for thyroid testing',body:['Thyroid blood tests usually require a venous blood sample. Fasting requirements depend on the specific panel and any other tests being collected at the same time. Certain medicines and supplements can affect thyroid test interpretation, so follow your clinician’s instructions rather than stopping medicines on your own.']}
 ]},
 {slug:'vitamin-d-test-guide',title:'Vitamin D Test Guide: What 25-OH Vitamin D Measures',description:'A practical overview of the 25-hydroxy vitamin D blood test, why it may be requested, and what patients should know before testing.',summary:'Learn why 25-hydroxy vitamin D is commonly measured and why the result should be considered together with clinical context.',readingTime:'3 min read',updated:'2026-09-14',searchQuery:'Vitamin D',sections:[
  {heading:'What does the vitamin D test measure?',body:['The most commonly used blood test for vitamin D status measures 25-hydroxy vitamin D, often written as 25-OH vitamin D. This form reflects vitamin D obtained from sunlight, food and supplements over time.']},
  {heading:'Why might a doctor request it?',body:['A clinician may request vitamin D testing when there are risk factors for low vitamin D, concerns involving bone health, certain symptoms, or as part of evaluation of another condition. Testing is not required for every healthy person, and the need for it depends on individual circumstances.']},
  {heading:'Before the test',body:['The test uses a blood sample. Fasting is generally not required for vitamin D alone, but a combined test panel may have different preparation instructions. Tell your clinician about supplements and medicines you take so the result can be interpreted appropriately.']}
 ]}
];

export function healthArticleBySlug(slug:string){return healthArticles.find(article=>article.slug===slug);}
