import crypto from 'crypto';
type Rule={limit:number;windowSeconds:number};const PREFIX='tg:public-api:v1';const memory=new Map<string,{count:number;resetAt:number}>();
function cfg(){const url=process.env.UPSTASH_REDIS_REST_URL?.trim().replace(/\/$/,'');const token=process.env.UPSTASH_REDIS_REST_TOKEN?.trim();return url&&token?{url,token}:null}
function hash(v:string){return crypto.createHash('sha256').update(v).digest('hex')}
export function requestIp(r:Request){return r.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||r.headers.get('x-real-ip')?.trim()||'unknown'}
async function redis(key:string,rule:Rule){const c=cfg();if(!c)return null;const res=await fetch(`${c.url}/pipeline`,{method:'POST',headers:{Authorization:`Bearer ${c.token}`,'Content-Type':'application/json'},body:JSON.stringify([['INCR',key],['EXPIRE',key,rule.windowSeconds,'NX'],['TTL',key]]),cache:'no-store'});if(!res.ok)throw new Error('RATE_LIMIT_BACKEND');const d=await res.json() as Array<{result?:unknown;error?:string}>;if(!Array.isArray(d)||d.some(x=>x.error))throw new Error('RATE_LIMIT_BACKEND');return{allowed:Number(d[0]?.result||0)<=rule.limit,retryAfterSeconds:Math.max(1,Number(d[2]?.result||rule.windowSeconds))}}
function local(key:string,rule:Rule){const now=Date.now(),old=memory.get(key),b=!old||old.resetAt<=now?{count:0,resetAt:now+rule.windowSeconds*1000}:old;b.count++;memory.set(key,b);if(memory.size>5000)for(const[k,v]of memory)if(v.resetAt<=now)memory.delete(k);return{allowed:b.count<=rule.limit,retryAfterSeconds:Math.max(1,Math.ceil((b.resetAt-now)/1000))}}
export async function enforceApiRateLimit(r:Request,scope:string,identity:string,rule:Rule){const key=`${PREFIX}:${scope}:${hash(identity)}`;try{return(await redis(key,rule))??local(key,rule)}catch{return local(key,rule)}}
export function rateLimitResponse(seconds:number){return new Response(JSON.stringify({error:'Too many requests. Please try again shortly.'}),{status:429,headers:{'Content-Type':'application/json','Retry-After':String(seconds),'Cache-Control':'no-store'}})}
