'use client';
import { useEffect,useMemo,useState } from 'react';

type Role='ADMIN'|'STAFF';
type Order={id:string;billNumber:string;createdAt:string;sampleEntryAt?:string;patient:{name:string;age:number|null;gender:string|null;phone:string};doctorName?:string;tests:string[];totalAmount:number;discount:number;paidAmount:number;balance:number;netAmount:number;paymentMode?:string;paymentModes?:string[];reportReady:boolean};
type Cat={name:string;sampleTypes?:string[]};
const paymentOptions=['CASH','UPI','CARD'];
export default function ManageOrders(){const[role,setRole]=useState<Role>('STAFF');const[orders,setOrders]=useState<Order[]>([]);const[catalog,setCatalog]=useState<Cat[]>([]);const[editing,setEditing]=useState<Order|null>(null);const[form,setForm]=useState<any>(null);const[error,setError]=useState('');const[q,setQ]=useState('');const[saving,setSaving]=useState(false);
 async function load(){setError('');try{const [s,o,c]=await Promise.all([fetch('/api/manual/session',{cache:'no-store'}),fetch('/api/admin/thyrocare/orders',{cache:'no-store'}),fetch('/api/admin/thyrocare/catalog',{cache:'no-store'})]);const sd=await s.json();const od=await o.json();const cd=await c.json();if(!s.ok)throw new Error(sd.error||'Sign in required.');if(!o.ok)throw new Error(od.error||'Unable to load orders.');setRole(sd.role);setOrders(od.orders||[]);setCatalog([...(cd.tests||[]),...(cd.packages||[])].map((x:any)=>({name:x.name,sampleTypes:x.sampleTypes||[]})))}catch(e){setError(e instanceof Error?e.message:'Unable to load orders.')}}useEffect(()=>{load()},[]);
 const shown=useMemo(()=>orders.filter(o=>!q||[o.billNumber,o.patient.name,o.patient.phone,o.tests.join(' ')].join(' ').toLowerCase().includes(q.toLowerCase())),[orders,q]);
 function sampleTypes(o:Order){const set=new Set<string>();for(const name of o.tests){const item=catalog.find(x=>x.name.toLowerCase()===name.toLowerCase());for(const s of item?.sampleTypes||[])set.add(s)}return [...set]}
 function begin(o:Order){setEditing(o);setForm({id:o.id,name:o.patient.name,age:o.patient.age??'',gender:o.patient.gender||'Female',phone:o.patient.phone,doctorName:o.doctorName||'',tests:o.tests.join(', '),totalAmount:o.totalAmount,discount:o.discount,paidAmount:o.paidAmount,paymentMode:o.paymentMode==='MULTIPLE'?'MULTIPLE':(o.paymentMode||'CASH'),paymentModes:o.paymentMode==='MULTIPLE'?(o.paymentModes||[]):[o.paymentMode||'CASH']});window.scrollTo({top:0,behavior:'smooth'})}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const tests=String(form.tests).split(/[,\n]/).map(x=>x.trim()).filter(Boolean);const r=await fetch('/api/admin/thyrocare/orders/manage',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,tests,paymentModes:form.paymentMode==='MULTIPLE'?form.paymentModes:[form.paymentMode]})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to update order.');setEditing(null);setForm(null);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update order.')}finally{setSaving(false)}}
 async function remove(o:Order){if(role!=='ADMIN')return;if(!confirm(`Delete order ${o.billNumber}? This cannot be undone.`))return;setError('');const r=await fetch('/api/admin/thyrocare/orders/manage',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:o.id})});const d=await r.json();if(!r.ok){setError(d.error||'Unable to delete order.');return}await load()}
 function toggleMode(m:string){setForm((x:any)=>({...x,paymentModes:x.paymentModes.includes(m)?x.paymentModes.filter((v:string)=>v!==m):[...x.paymentModes,m]}))}
 return <main style={{minHeight:'100vh',background:'#f5f7f9',fontFamily:'Arial,sans-serif',padding:22,color:'#1f2937'}}><div style={{maxWidth:1400,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontSize:12,fontWeight:900,color:'#087f6f'}}>THYROCARE • ORDER MANAGEMENT</div><h1 style={{margin:'5px 0'}}>Manage Orders</h1><div style={{color:'#64748b'}}>Both Admin and Staff can edit. Only Admin can delete.</div></div><input value={q} onChange={e=>setQ(e.target.value)} style={{...input,width:330}} placeholder="Search bill, patient, mobile or test"/></div>{error&&<div style={err}>{error}</div>}
 {editing&&form&&<form onSubmit={save} style={{...card,marginTop:16}}><h2 style={{marginTop:0}}>Edit {editing.billNumber}</h2><div style={grid3}><label style={label}>Patient Name<input required style={input} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label style={label}>Age<input required type="number" style={input} value={form.age} onChange={e=>setForm({...form,age:e.target.value})}/></label><label style={label}>Gender<select style={input} value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option>Female</option><option>Male</option><option>Others</option></select></label><label style={label}>Mobile<input required maxLength={10} style={input} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value.replace(/\D/g,'')})}/></label><label style={label}>Doctor<input style={input} value={form.doctorName} onChange={e=>setForm({...form,doctorName:e.target.value})}/></label><label style={label}>Payment Mode<select style={input} value={form.paymentMode} onChange={e=>setForm({...form,paymentMode:e.target.value,paymentModes:e.target.value==='MULTIPLE'?[]:[e.target.value]})}><option value="CASH">Cash</option><option value="UPI">UPI</option><option value="CARD">Card</option><option value="MULTIPLE">Multiple</option></select></label></div>{form.paymentMode==='MULTIPLE'&&<div style={{display:'flex',gap:14,marginTop:12}}>{paymentOptions.map(m=><label key={m}><input type="checkbox" checked={form.paymentModes.includes(m)} onChange={()=>toggleMode(m)}/> {m}</label>)}</div>}<label style={label}>Tests / Packages<textarea rows={3} style={{...input,resize:'vertical'}} value={form.tests} onChange={e=>setForm({...form,tests:e.target.value})}/></label><div style={grid3}><label style={label}>Total<input type="number" style={input} value={form.totalAmount} onChange={e=>setForm({...form,totalAmount:e.target.value})}/></label><label style={label}>Discount<input type="number" style={input} value={form.discount} onChange={e=>setForm({...form,discount:e.target.value})}/></label><label style={label}>Paid<input type="number" style={input} value={form.paidAmount} onChange={e=>setForm({...form,paidAmount:e.target.value})}/></label></div><div style={{display:'flex',gap:8,marginTop:14}}><button disabled={saving} style={primary}>{saving?'Saving…':'Save Changes'}</button><button type="button" onClick={()=>{setEditing(null);setForm(null)}} style={secondary}>Cancel</button></div></form>}
 <div style={{...card,marginTop:16,overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:1100}}><thead><tr>{['Bill / Time','Patient','Tests','Sample Requirements','Amount','Payment','Report','Actions'].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{shown.map(o=><tr key={o.id}><td style={td}><b>{o.billNumber}</b><div style={sub}>{new Date(o.sampleEntryAt||o.createdAt).toLocaleString('en-IN')}</div></td><td style={td}><b>{o.patient.name}</b><div style={sub}>{o.patient.age??'-'} / {o.patient.gender||'-'} • {o.patient.phone}</div><div style={sub}>Doctor: {o.doctorName||'—'}</div></td><td style={td}>{o.tests.join(', ')}</td><td style={td}>{sampleTypes(o).length?sampleTypes(o).map(s=><span key={s} style={pill}>{s}</span>):'—'}</td><td style={td}>₹{o.netAmount}<div style={sub}>Paid ₹{o.paidAmount} • Balance ₹{o.balance}</div></td><td style={td}>{o.paymentMode||'—'}</td><td style={td}>{o.reportReady?'Ready':'Pending'}</td><td style={td}><div style={{display:'flex',gap:6}}><button onClick={()=>begin(o)} style={editBtn}>Edit</button>{role==='ADMIN'&&<button onClick={()=>remove(o)} style={deleteBtn}>Delete</button>}</div></td></tr>)}{shown.length===0&&<tr><td colSpan={8} style={td}>No orders found.</td></tr>}</tbody></table></div></div></main>}
const card={background:'#fff',border:'1px solid #dfe5e9',borderRadius:12,padding:16,boxShadow:'0 4px 18px rgba(15,23,42,.05)'} as const;const label={display:'block',fontSize:12,fontWeight:800} as const;const input={display:'block',width:'100%',boxSizing:'border-box' as const,marginTop:5,padding:'10px 11px',border:'1px solid #cfd8df',borderRadius:8,font:'inherit',background:'#fff'} as const;const grid3={display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:10} as const;const th={textAlign:'left' as const,padding:'10px 8px',borderBottom:'1px solid #dbe3e8',background:'#fafcfd',fontSize:12};const td={padding:'10px 8px',borderBottom:'1px solid #e5e7eb',verticalAlign:'top' as const,fontSize:12};const sub={fontSize:10,color:'#64748b',marginTop:3};const pill={display:'inline-block',padding:'4px 7px',margin:'2px',borderRadius:999,background:'#e7f7f3',color:'#0d5f54',fontSize:10,fontWeight:900};const primary={border:0,borderRadius:8,padding:'10px 14px',background:'#087f6f',color:'#fff',fontWeight:900,cursor:'pointer'} as const;const secondary={border:'1px solid #d5dce1',borderRadius:8,padding:'10px 14px',background:'#fff',fontWeight:800,cursor:'pointer'} as const;const editBtn={...primary,padding:'7px 10px',background:'#1688e8'};const deleteBtn={...primary,padding:'7px 10px',background:'#dc2626'};const err={marginTop:14,padding:12,borderRadius:10,background:'#fff1f2',border:'1px solid #fecdd3',color:'#9f1239'} as const;
