'use client';

import { useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';

type Role='ADMIN'|'STAFF';
export default function ThyrocareManualLogin(){
 const router=useRouter();const params=useSearchParams();const[phone,setPhone]=useState('9701162302');const[role,setRole]=useState<Role>('STAFF');const[password,setPassword]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');try{const r=await fetch('/api/manual/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone,role,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to sign in.');const next=params.get('next')||'/manual';router.replace(next);router.refresh()}catch(e){setError(e instanceof Error?e.message:'Unable to sign in.')}finally{setLoading(false)}}
 return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'#f3f7f5',fontFamily:'Arial,sans-serif',padding:20}}><form onSubmit={submit} style={{width:'100%',maxWidth:430,background:'#fff',padding:26,borderRadius:16,border:'1px solid #dce6e2',boxShadow:'0 18px 45px rgba(15,23,42,.08)'}}><div style={{fontSize:13,fontWeight:900,color:'#087f6f'}}>THYROCARE • SECURE MANUAL DASHBOARD</div><h1 style={{margin:'8px 0 6px'}}>Sign in</h1><p style={{margin:'0 0 20px',color:'#64748b',lineHeight:1.5}}>Use the registered mobile login ID and the password assigned for your role.</p>{error&&<div style={{padding:11,borderRadius:9,background:'#fff1f2',border:'1px solid #fecdd3',color:'#9f1239',marginBottom:12}}>{error}</div>}<label style={label}>Login ID / Mobile<input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,'').slice(0,10))} inputMode="tel" maxLength={10} required style={input}/></label><label style={label}>Role<select value={role} onChange={e=>setRole(e.target.value as Role)} style={input}><option value="STAFF">Staff</option><option value="ADMIN">Admin</option></select></label><label style={label}>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password" style={input} placeholder="Enter password"/></label><button disabled={loading} style={{width:'100%',marginTop:18,padding:'12px 14px',border:0,borderRadius:9,background:'#087f6f',color:'#fff',fontWeight:900,cursor:'pointer'}}>{loading?'Signing in…':'Sign in'}</button><div style={{marginTop:16,fontSize:12,color:'#64748b',lineHeight:1.5}}>Staff can create and edit orders. Admin can additionally manage Tests/Packages and delete orders.</div></form></main>
}
const label={display:'block',fontSize:13,fontWeight:800,marginTop:12} as const;const input={display:'block',width:'100%',boxSizing:'border-box' as const,marginTop:6,padding:'11px 12px',border:'1px solid #cbd5e1',borderRadius:9,font:'inherit',background:'#fff'} as const;
