import { NextResponse } from 'next/server';
import { z } from 'zod';
import { prisma } from '@/lib/prisma';
import { writeAdminAudit } from '@/lib/admin-audit';

export const dynamic='force-dynamic';export const maxDuration=60;
const schema=z.object({fileName:z.string().min(1).max(180),fileData:z.string().min(20)});const MAX=3*1024*1024;
function bytes(dataUrl:string){const comma=dataUrl.indexOf(',');const b64=comma>=0?dataUrl.slice(comma+1):dataUrl;const padding=b64.endsWith('==')?2:b64.endsWith('=')?1:0;return Math.floor((b64.length*3)/4)-padding}
export async function GET(_request:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const row=await prisma.booking.findFirst({where:{id,createdByAdmin:'THYROCARE_MANUAL'},select:{reportName:true,reportData:true}});if(!row?.reportData)return NextResponse.json({error:'Report not available.'},{status:404});const match=row.reportData.match(/^data:application\/pdf;base64,(.+)$/s);if(!match)return NextResponse.json({error:'Invalid stored report.'},{status:500});const data=Buffer.from(match[1],'base64');return new NextResponse(data,{headers:{'Content-Type':'application/pdf','Content-Disposition':`inline; filename="${(row.reportName||'report.pdf').replace(/"/g,'')}"`,'Cache-Control':'private, no-store, max-age=0'}})}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){try{const {id}=await params;const body=schema.parse(await request.json());if(!body.fileName.toLowerCase().endsWith('.pdf'))return NextResponse.json({error:'Only PDF reports can be uploaded.'},{status:400});if(!body.fileData.startsWith('data:application/pdf;base64,'))return NextResponse.json({error:'Invalid PDF file.'},{status:400});if(bytes(body.fileData)>MAX)return NextResponse.json({error:'PDF must be smaller than 3 MB.'},{status:413});const existing=await prisma.booking.findFirst({where:{id,createdByAdmin:'THYROCARE_MANUAL'}});if(!existing)return NextResponse.json({error:'Manual order not found.'},{status:404});const now=new Date();await prisma.booking.update({where:{id},data:{reportName:body.fileName,reportData:body.fileData,reportReadyAt:now,workflowStatus:'REPORT_READY',status:'CONFIRMED'}});await writeAdminAudit(request,{action:existing.reportData?'THYROCARE_REPORT_REPLACED':'THYROCARE_REPORT_UPLOADED',entityType:'Booking',entityId:id,summary:`${existing.reportData?'Replaced':'Uploaded'} Thyrocare manual report ${body.fileName}`,metadata:{fileName:body.fileName,fileBytes:bytes(body.fileData)}});return NextResponse.json({ok:true,reportName:body.fileName,reportReadyAt:now.toISOString()});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:'Invalid report upload.'},{status:400});console.error(error);return NextResponse.json({error:'Unable to upload report.'},{status:500})}}
