import { NextResponse } from 'next/server';
import { z } from 'zod';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { prisma } from '@/lib/prisma';
import { writeAdminAudit } from '@/lib/admin-audit';

export const dynamic='force-dynamic';export const maxDuration=60;
const schema=z.object({fileName:z.string().min(1).max(180),fileData:z.string().min(20),reportType:z.enum(['FULL','PARTIAL']).optional().default('FULL'),addPageNumbers:z.boolean().optional().default(false)});const MAX=3*1024*1024;
function bytes(dataUrl:string){const comma=dataUrl.indexOf(',');const b64=comma>=0?dataUrl.slice(comma+1):dataUrl;const padding=b64.endsWith('==')?2:b64.endsWith('=')?1:0;return Math.floor((b64.length*3)/4)-padding}
function parseMeta(value:string|null){try{return value?JSON.parse(value) as Record<string,unknown>:{} }catch{return {}}}
async function replaceExistingPageNumbers(dataUrl:string){const match=dataUrl.match(/^data:application\/pdf;base64,(.+)$/s);if(!match)throw new Error('INVALID_PDF');const source=Buffer.from(match[1],'base64');const pdf=await PDFDocument.load(source);const font=await pdf.embedFont(StandardFonts.Helvetica);const pages=pdf.getPages();const total=pages.length;for(let i=0;i<total;i++){const page=pages[i];const {width}=page.getSize();const footerWidth=132;const footerHeight=18;const footerRight=12;const footerY=7;page.drawRectangle({x:Math.max(0,width-footerWidth-footerRight),y:2,width:footerWidth,height:footerHeight,color:rgb(1,1,1)});const text=`Page: ${i+1} of ${total}`;const size=9;const textWidth=font.widthOfTextAtSize(text,size);page.drawText(text,{x:Math.max(12,width-footerRight-textWidth),y:footerY,size,font,color:rgb(0.25,0.25,0.25)});}const output=await pdf.save();return `data:application/pdf;base64,${Buffer.from(output).toString('base64')}`}
export async function GET(_request:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const row=await prisma.booking.findFirst({where:{id,createdByAdmin:'THYROCARE_MANUAL'},select:{reportName:true,reportData:true}});if(!row?.reportData)return NextResponse.json({error:'Report not available.'},{status:404});const match=row.reportData.match(/^data:application\/pdf;base64,(.+)$/s);if(!match)return NextResponse.json({error:'Invalid stored report.'},{status:500});const data=Buffer.from(match[1],'base64');return new NextResponse(data,{headers:{'Content-Type':'application/pdf','Content-Disposition':`inline; filename="${(row.reportName||'report.pdf').replace(/"/g,'')}"`,'Cache-Control':'private, no-store, max-age=0'}})}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){try{const {id}=await params;const body=schema.parse(await request.json());if(!body.fileName.toLowerCase().endsWith('.pdf'))return NextResponse.json({error:'Only PDF reports can be uploaded.'},{status:400});if(!body.fileData.startsWith('data:application/pdf;base64,'))return NextResponse.json({error:'Invalid PDF file.'},{status:400});if(bytes(body.fileData)>MAX)return NextResponse.json({error:'PDF must be smaller than 3 MB.'},{status:413});const existing=await prisma.booking.findFirst({where:{id,createdByAdmin:'THYROCARE_MANUAL'}});if(!existing)return NextResponse.json({error:'Manual order not found.'},{status:404});let finalData=body.fileData;if(body.addPageNumbers){try{finalData=await replaceExistingPageNumbers(body.fileData)}catch{return NextResponse.json({error:'Unable to replace page numbers in this PDF. Please check that the PDF is valid and not password-protected.'},{status:400})}}const now=new Date();const old=parseMeta(existing.adminNotes);const meta={...old,reportType:body.reportType,reportUploadedAt:now.toISOString(),reportPageNumbersReplaced:body.addPageNumbers};const isFull=body.reportType==='FULL';await prisma.booking.update({where:{id},data:{reportName:body.fileName,reportData:finalData,reportReadyAt:isFull?now:null,workflowStatus:isFull?'REPORT_READY':existing.workflowStatus==='REPORT_READY'?'PROCESSING':existing.workflowStatus,status:'CONFIRMED',adminNotes:JSON.stringify(meta)}});await writeAdminAudit(request,{action:existing.reportData?'THYROCARE_REPORT_REPLACED':'THYROCARE_REPORT_UPLOADED',entityType:'Booking',entityId:id,summary:`${existing.reportData?'Replaced':'Uploaded'} ${body.reportType.toLowerCase()} Thyrocare report ${body.fileName}`,metadata:{fileName:body.fileName,fileBytes:bytes(finalData),reportType:body.reportType,pageNumbersReplaced:body.addPageNumbers}});return NextResponse.json({ok:true,reportName:body.fileName,reportType:body.reportType,reportReady:isFull,reportReadyAt:isFull?now.toISOString():null,pageNumbersReplaced:body.addPageNumbers});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:'Invalid report upload.'},{status:400});console.error(error);return NextResponse.json({error:'Unable to upload report.'},{status:500})}}
