'use client';

import { useEffect, useMemo, useState } from 'react';

type LiveRow={bookingId:string;workflowStatus:string;patientName:string;patientPhone:string;technicianId:string;technicianName:string;latitude:number;longitude:number;accuracy:number|null;speed:number|null;heading:number|null;recordedAt:string};

export default function AdminTrackingPage(){
 const[rows,setRows]=useState<LiveRow[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function load(){try{const r=await fetch('/api/admin/tracking',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load live tracking.');setRows(j.active||[]);setError('');if(!selected&&j.active?.[0])setSelected(j.active[0].bookingId)}catch(e){setError(e instanceof Error?e.message:'Unable to load live tracking.')}finally{setLoading(false)}}
 useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[]);
 const current=useMemo(()=>rows.find(r=>r.bookingId===selected)||rows[0],[rows,selected]);
 const age=current?Math.max(0,Math.round((Date.now()-new Date(current.recordedAt).getTime())/1000)):0;
 const fresh=age<=60;
 return <main style={{minHeight:'100vh',background:'#f4f8f6',padding:24,fontFamily:'Arial,sans-serif',color:'#12352f'}}><div style={{maxWidth:1250,margin:'0 auto'}}>
  <header style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap',marginBottom:18}}><div><div style={{fontSize:12,fontWeight:900,color:'#087f6f'}}>TG LABS • LIVE OPERATIONS</div><h1 style={{margin:'6px 0'}}>Technician Live Tracking</h1><p style={{margin:0,color:'#667a74'}}>Tracking is active only from On the Way until Sample Submitted at Lab. Location refreshes every 15 seconds while the technician portal is open.</p></div><a href="/admin" style={{fontWeight:800,color:'#087f6f'}}>← Admin dashboard</a></header>
  {error&&<div style={{background:'#fff0f0',border:'1px solid #e9b7b7',padding:14,borderRadius:12,marginBottom:14}}>{error}</div>}
  {loading?<div style={card}>Loading live locations…</div>:!rows.length?<div style={{...card,textAlign:'center',padding:40}}>No technician is currently transmitting a live location.</div>:<div style={{display:'grid',gridTemplateColumns:'minmax(300px,.75fr) minmax(0,1.5fr)',gap:18}}>
   <aside style={{display:'grid',gap:10,alignContent:'start'}}>{rows.map(r=>{const seconds=Math.max(0,Math.round((Date.now()-new Date(r.recordedAt).getTime())/1000));return <button key={r.bookingId} onClick={()=>setSelected(r.bookingId)} style={{...card,textAlign:'left',cursor:'pointer',border:r.bookingId===current?.bookingId?'2px solid #087f6f':'1px solid #dfe9e5',background:r.bookingId===current?.bookingId?'#effaf7':'#fff'}}><div style={{fontSize:11,fontWeight:900,color:'#087f6f'}}>{label(r.workflowStatus)}</div><h3 style={{margin:'6px 0'}}>{r.technicianName}</h3><div><b>Patient:</b> {r.patientName}</div><div style={{fontSize:12,color:seconds<=60?'#087f6f':'#9a5b11',marginTop:5}}>{seconds<=60?'● LIVE':'● DELAYED'} • {seconds}s ago</div></button>})}</aside>
   {current&&<section style={card}><div style={{display:'flex',justifyContent:'space-between',gap:14,flexWrap:'wrap',marginBottom:12}}><div><div style={{fontSize:12,fontWeight:900,color:'#087f6f'}}>{label(current.workflowStatus)}</div><h2 style={{margin:'5px 0'}}>{current.technicianName}</h2><div>Patient: {current.patientName}</div></div><div style={{textAlign:'right'}}><b style={{color:fresh?'#087f6f':'#9a5b11'}}>{fresh?'LIVE':'DELAYED'}</b><br/><small>Updated {age}s ago</small></div></div><iframe title="Technician live Google Map" src={`https://www.google.com/maps?q=${current.latitude},${current.longitude}&z=16&output=embed`} style={{width:'100%',height:520,border:0,borderRadius:14}} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,marginTop:14}}><Info k="Latitude" v={current.latitude.toFixed(6)}/><Info k="Longitude" v={current.longitude.toFixed(6)}/><Info k="Accuracy" v={current.accuracy!=null?`±${Math.round(current.accuracy)} m`:'—'}/><Info k="Speed" v={current.speed!=null?`${(current.speed*3.6).toFixed(1)} km/h`:'—'}/></div><a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${current.latitude},${current.longitude}`} style={{display:'inline-block',marginTop:14,padding:'11px 14px',borderRadius:10,background:'#087f6f',color:'#fff',fontWeight:800,textDecoration:'none'}}>Open live point in Google Maps ↗</a></section>}
  </div>}
 </div><style>{`@media(max-width:850px){main>div>div{grid-template-columns:1fr!important}}`}</style></main>
}
const card:React.CSSProperties={background:'#fff',border:'1px solid #dfe9e5',borderRadius:16,padding:16,boxShadow:'0 8px 24px rgba(12,71,61,.05)'};
function label(v:string){return ({ON_THE_WAY:'On the Way',REACHED_PATIENT:'Reached Patient',SAMPLE_COLLECTED:'Sample Collected • Returning to Lab'} as Record<string,string>)[v]||v}
function Info({k,v}:{k:string;v:string}){return <div style={{padding:12,borderRadius:12,background:'#f6faf9'}}><small style={{display:'block',color:'#71817d'}}>{k}</small><b>{v}</b></div>}
