ALTER TABLE "Patient" ADD COLUMN IF NOT EXISTS "age" INTEGER;
ALTER TABLE "Patient" ADD COLUMN IF NOT EXISTS "gender" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "technician" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "reportName" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "reportData" TEXT;
