'use client';
import { useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';

type Identity={phone:string;role:'ADMIN'|'STAFF'};
export default function PasswordPage(){
 const router=useRouter();const[id,setId]=useState<Identity|null>(null);const[currentPassword,setCurrent]=useState('');const[newPassword,setNew]=useState('');const[confirm,setConfirm]=useState('');const[error,setError]=useState('');const[ok,setOk]=useState('');const[loading,setLoading]=useState(false);
 useEffect(()=>{fetch('/api/manual/session',{cache:'no-store'}).then(async r=>{if(!r.ok){router.replace('/manual/login?next=%2Fmanual%2Fpassword');return}setId(await r.json())}).catch(()=>router.replace('/manual/login?next=%2Fmanual%2Fpassword'))},[router]);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setOk('');if(newPassword!==confirm){setError('New password and confirmation do not match.');return}setLoading(true);try{const r=await fetch('/api/manual/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword,newPassword})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to change password.');setCurrent('');setNew('');setConfirm('');setOk(`${d.role==='ADMIN'?'Admin':'Staff'} password changed successfully.`)}catch(e){setError(e instanceof Error?e.message:'Unable to change password.')}finally{setLoading(false)}}
 if(!id)return <main style={page}><div>Loading…</div></main>;
 return <main style={page}><form onSubmit={submit} style={card}><div style={{fontSize:12,fontWeight:900,color:'#087f6f'}}>THYROCARE • SECURITY</div><h1 style={{margin:'8px 0 4px'}}>Change Password</h1><p style={{margin:'0 0 18px',color:'#64748b',lineHeight:1.5}}>Signed in as <b>{id.role}</b> • {id.phone}. This changes only your own role password.</p>{error&&<div style={err}>{error}</div>}{ok&&<div style={success}>{ok}</div>}<label style={label}>Current Password<input type="password" value={currentPassword} onChange={e=>setCurrent(e.target.value)} required autoComplete="current-password" style={input}/></label><label style={label}>New Password<input type="password" value={newPassword} onChange={e=>setNew(e.target.value)} required minLength={10} autoComplete="new-password" style={input} placeholder="Minimum 10 characters"/></label><label style={label}>Confirm New Password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} required minLength={10} autoComplete="new-password" style={input}/></label><div style={{display:'flex',gap:10,marginTop:18}}><button disabled={loading} style={primary}>{loading?'Changing…':'Change Password'}</button><button type="button" onClick={()=>router.push('/manual')} style={secondary}>Back to Dashboard</button></div><div style={{marginTop:16,fontSize:12,color:'#64748b',lineHeight:1.5}}>For security, the current password is required. Staff can change the Staff password; Admin can change the Admin password.</div></form></main>
}
const page={minHeight:'100vh',display:'grid',placeItems:'center',background:'#f3f7f5',fontFamily:'Arial,sans-serif',padding:20} as const;const card={width:'100%',maxWidth:460,background:'#fff',padding:26,borderRadius:16,border:'1px solid #dce6e2',boxShadow:'0 18px 45px rgba(15,23,42,.08)'} as const;const label={display:'block',fontSize:13,fontWeight:800,marginTop:12} as const;const input={display:'block',width:'100%',boxSizing:'border-box',marginTop:6,padding:'11px 12px',border:'1px solid #cbd5e1',borderRadius:9,font:'inherit',background:'#fff'} as const;const primary={padding:'11px 14px',border:0,borderRadius:9,background:'#087f6f',color:'#fff',fontWeight:900,cursor:'pointer'} as const;const secondary={padding:'11px 14px',border:'1px solid #cbd5e1',borderRadius:9,background:'#fff',color:'#334155',fontWeight:800,cursor:'pointer'} as const;const err={padding:11,borderRadius:9,background:'#fff1f2',border:'1px solid #fecdd3',color:'#9f1239',marginBottom:12} as const;const success={padding:11,borderRadius:9,background:'#ecfdf5',border:'1px solid #a7f3d0',color:'#065f46',marginBottom:12} as const;
