'use client';

import { FormEvent,useEffect,useRef,useState } from 'react';
import { ConfirmationResult,RecaptchaVerifier,signInWithPhoneNumber,signOut } from 'firebase/auth';
import { getFirebaseAuth } from '@/lib/firebase';
import { firebaseAuthErrorMessage } from '@/lib/firebase-auth-errors';
import { useOtpCooldown } from '@/lib/use-otp-cooldown';

type Role='ADMIN'|'STAFF';
export default function ThyrocareForgotPassword(){
 const verifier=useRef<RecaptchaVerifier|null>(null);const[role,setRole]=useState<Role>('STAFF');const[phone,setPhone]=useState('');const[confirmation,setConfirmation]=useState<ConfirmationResult|null>(null);const[otp,setOtp]=useState('');const[verifiedToken,setVerifiedToken]=useState('');const[newPassword,setNewPassword]=useState('');const[confirmPassword,setConfirmPassword]=useState('');const[message,setMessage]=useState('');const[loading,setLoading]=useState(false);const{coolingDown,remaining,startCooldown}=useOtpCooldown();
 function resetRecaptcha(){try{verifier.current?.clear()}catch{}verifier.current=null;const el=document.getElementById('thyrocare-reset-recaptcha');if(el)el.innerHTML=''}
 useEffect(()=>()=>resetRecaptcha(),[]);
 function normalizedPhone(){if(!/^[6-9]\d{9}$/.test(phone))throw Object.assign(new Error('INVALID_PHONE'),{code:'auth/invalid-phone-number'});return `+91${phone}`}
 async function sendOtp(e:FormEvent){e.preventDefault();if(coolingDown)return;setLoading(true);setMessage('');try{resetRecaptcha();const auth=getFirebaseAuth();verifier.current=new RecaptchaVerifier(auth,'thyrocare-reset-recaptcha',{size:'invisible'});await verifier.current.render();const result=await signInWithPhoneNumber(auth,normalizedPhone(),verifier.current);setConfirmation(result);startCooldown();setMessage('OTP sent to the registered mobile number. Enter the 6-digit code.')}catch(error){resetRecaptcha();setMessage(firebaseAuthErrorMessage(error,'Unable to send OTP safely. Please try again.'))}finally{setLoading(false)}}
 async function verifyOtp(e:FormEvent){e.preventDefault();if(!confirmation)return;setLoading(true);setMessage('');try{const credential=await confirmation.confirm(otp.trim());const token=await credential.user.getIdToken(true);setVerifiedToken(token);resetRecaptcha();setMessage('Mobile verified. Enter a new password for the selected role.')}catch(error){setMessage(firebaseAuthErrorMessage(error,'Unable to verify this OTP. Request a new code and try again.'))}finally{setLoading(false)}}
 async function resetPassword(e:FormEvent){e.preventDefault();setLoading(true);setMessage('');try{if(newPassword!==confirmPassword)throw new Error('Passwords do not match.');const r=await fetch('/api/manual/password/reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idToken:verifiedToken,role,newPassword})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to reset password.');try{await signOut(getFirebaseAuth())}catch{}setMessage(`${role==='ADMIN'?'Admin':'Staff'} password reset successfully. You can sign in with the new password.`);setVerifiedToken('');setConfirmation(null);setOtp('');setNewPassword('');setConfirmPassword('')}catch(error){setMessage(error instanceof Error?error.message:'Unable to reset password.')}finally{setLoading(false)}}
 return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'#f3f7f5',fontFamily:'Arial,sans-serif',padding:20}}><section style={{width:'100%',maxWidth:450,background:'#fff',padding:26,borderRadius:16,border:'1px solid #dce6e2',boxShadow:'0 18px 45px rgba(15,23,42,.08)'}}><div style={{fontSize:13,fontWeight:900,color:'#087f6f'}}>THYROCARE • PASSWORD RECOVERY</div><h1 style={{margin:'8px 0 6px'}}>Forgot password</h1><p style={{margin:'0 0 18px',color:'#64748b',lineHeight:1.5}}>Verify the registered mobile number by SMS OTP, then set a new password for Admin or Staff.</p>{message&&<div style={{padding:11,borderRadius:9,background:'#f8fafc',border:'1px solid #cbd5e1',marginBottom:12,lineHeight:1.45}}>{message}</div>}<label style={label}>Reset password for<select value={role} onChange={e=>setRole(e.target.value as Role)} style={input} disabled={!!verifiedToken}><option value="STAFF">Staff</option><option value="ADMIN">Admin</option></select></label>{!confirmation&&!verifiedToken&&<form onSubmit={sendOtp}><label style={label}>Registered mobile number<input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,'').slice(0,10))} inputMode="tel" autoComplete="tel" maxLength={10} required style={input}/></label><button disabled={loading||coolingDown||phone.length!==10} style={primary}>{loading?'Sending OTP…':coolingDown?`Try again in ${remaining}s`:'Send recovery OTP'}</button></form>}{confirmation&&!verifiedToken&&<form onSubmit={verifyOtp}><label style={label}>6-digit OTP<input value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="one-time-code" maxLength={6} required style={{...input,letterSpacing:5,fontSize:20}}/></label><button disabled={loading||otp.length!==6} style={primary}>{loading?'Verifying…':'Verify OTP'}</button></form>}{verifiedToken&&<form onSubmit={resetPassword}><label style={label}>New Password<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} minLength={10} required autoComplete="new-password" style={input}/></label><label style={label}>Confirm New Password<input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} minLength={10} required autoComplete="new-password" style={input}/></label><button disabled={loading} style={primary}>{loading?'Saving…':'Reset Password'}</button></form>}<div id="thyrocare-reset-recaptcha"/><a href="/manual/login" style={{display:'inline-block',marginTop:18,color:'#087f6f',fontWeight:800,textDecoration:'none'}}>← Back to sign in</a><p style={{fontSize:12,color:'#64748b',marginTop:16,lineHeight:1.5}}>For security, an OTP is always required before a forgotten Admin or Staff password can be replaced.</p></section></main>
}
const label={display:'block',fontSize:13,fontWeight:800,marginTop:12} as const;const input={display:'block',width:'100%',boxSizing:'border-box' as const,marginTop:6,padding:'11px 12px',border:'1px solid #cbd5e1',borderRadius:9,font:'inherit',background:'#fff'} as const;const primary={width:'100%',marginTop:18,padding:'12px 14px',border:0,borderRadius:9,background:'#087f6f',color:'#fff',fontWeight:900,cursor:'pointer'} as const;
