'use client';
import {useEffect} from 'react';
import {usePathname} from 'next/navigation';

type OrderLite={id:string;billNumber:string;patient?:{phone?:string};reportAvailable?:boolean;originalBillAvailable?:boolean};

export default function BillReportShareEnhancer(){
 const pathname=usePathname();
 useEffect(()=>{if(pathname!=='/manual')return;let stopped=false;const orderMap=new Map<string,OrderLite>();
  const read=(f:File)=>new Promise<string>((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result||''));r.onerror=()=>no(new Error('Unable to read PDF'));r.readAsDataURL(f)});
  async function loadOrders(){try{const r=await fetch('/api/admin/thyrocare/orders',{cache:'no-store'});const d=await r.json();if(!r.ok)return;for(const o of d.orders||[]){if(o.billNumber)orderMap.set(String(o.billNumber).toUpperCase(),o)}inject()}catch{}}
  async function uploadMany(id:string,files:File[],btn:HTMLElement){if(!files.length)return;btn.textContent='Uploading bill(s)…';try{for(const f of files){if(f.type!=='application/pdf')throw new Error('Original bills must be PDF files.');const fileData=await read(f);const r=await fetch(`/api/admin/thyrocare/orders/${encodeURIComponent(id)}/original-bill`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fileName:f.name,fileData})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to upload bill.')}location.reload()}catch(e){alert(e instanceof Error?e.message:'Unable to upload bills.');btn.textContent='Upload Original Bill(s)'}}
  async function shareFile(url:string,name:string,phone:string,label:string){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`No ${label.toLowerCase()} available.`);const blob=await r.blob();const file=new File([blob],name,{type:'application/pdf'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({files:[file],title:`Thyrocare ${label}`,text:`Thyrocare ${label} for ${phone}`});return}window.open(url,'_blank');window.open(`https://wa.me/91${phone}?text=${encodeURIComponent(`Thyrocare ${label} is ready. Please attach the opened PDF in this WhatsApp chat.`)}`,'_blank')}catch(e){if((e as any)?.name!=='AbortError')alert(e instanceof Error?e.message:'Unable to share file.')}}
  function inject(){if(stopped)return;const h=[...document.querySelectorAll('h2')].find(x=>x.textContent?.includes('Orders / Bills List'));const table=h?.parentElement?.parentElement?.querySelector('table');if(!table)return;for(const row of [...table.querySelectorAll('tbody tr')]){const c=row.querySelectorAll('td');if(c.length<2)continue;const rowText=(row.textContent||'').toUpperCase();const billNumber=rowText.match(/OP\d+/)?.[0];const directId=rowText.match(/THY-[A-Z0-9-]+/)?.[0];const mapped=billNumber?orderMap.get(billNumber):undefined;const id=mapped?.id||directId;const phone=(mapped?.patient?.phone||rowText.match(/\b\d{10}\b/)?.[0]||'').replace(/\D/g,'').slice(-10);if(!id||phone.length!==10)continue;const action=c[0] as HTMLTableCellElement;if(action.querySelector('[data-bill-share]'))continue;const wrap=document.createElement('div');wrap.dataset.billShare='1';wrap.style.cssText='display:flex;flex-wrap:wrap;gap:5px;margin-top:6px;min-width:160px';
    const upload=document.createElement('label');upload.textContent='Upload Original Bill(s)';upload.style.cssText='cursor:pointer;padding:6px 8px;border-radius:6px;background:#e0f2fe;color:#075985;font-size:10px;font-weight:800;text-align:center';const inp=document.createElement('input');inp.type='file';inp.accept='application/pdf';inp.multiple=true;inp.hidden=true;inp.onchange=()=>uploadMany(id,Array.from(inp.files||[]),upload);upload.appendChild(inp);
    const mk=(text:string,enabled:boolean,fn:()=>void)=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.disabled=!enabled;b.style.cssText=`padding:6px 8px;border:1px solid ${enabled?'#16a34a':'#94a3b8'};border-radius:6px;background:${enabled?'#16a34a':'#e2e8f0'};color:${enabled?'#fff':'#64748b'};font-size:10px;font-weight:800;cursor:${enabled?'pointer':'not-allowed'}`;if(enabled)b.onclick=fn;return b};
    const reportEnabled=Boolean(mapped?.reportAvailable)||/\b(FULL|PARTIAL)\b/.test(rowText);
    const billEnabled=Boolean(mapped?.originalBillAvailable)||rowText.includes('ORIGINAL BILL');
    const reportButton=mk('Send Report WhatsApp',reportEnabled,()=>shareFile(`/api/admin/thyrocare/orders/${encodeURIComponent(id)}/report`,'Thyrocare-Report.pdf',phone,'Report'));
    const billButton=mk('Send Bill WhatsApp',billEnabled,()=>shareFile(`/api/admin/thyrocare/orders/${encodeURIComponent(id)}/original-bill`,'Thyrocare-Original-Bill.pdf',phone,'Original Bill'));
    wrap.append(upload,reportButton,billButton);action.appendChild(wrap)}}
  loadOrders();inject();const ob=new MutationObserver(inject);ob.observe(document.body,{childList:true,subtree:true});return()=>{stopped=true;ob.disconnect()}
 },[pathname]);return null
}
