'use client';

import { useEffect, useMemo, useState } from 'react';

type Booking={id:string;source:string;mode:string;collectionDate:string;slot:string;status:string;paymentStatus:string;totalAmount:number;technician?:string|null;reportName?:string|null;patient:{name:string;phone:string;age?:number|null;gender?:string|null;email?:string|null};items:{test:{id:string;name:string}}[]};
const field:React.CSSProperties={padding:'11px 13px',border:'1px solid #cddbd6',borderRadius:10,background:'#fff'};

export default function BookingManagementPage(){
 const [rows,setRows]=useState<Booking[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[status,setStatus]=useState('ALL'),[payment,setPayment]=useState('ALL'),[source,setSource]=useState('ALL');
 useEffect(()=>{fetch('/api/admin/bookings').then(r=>r.json()).then(j=>setRows(j.bookings||[])).finally(()=>setLoading(false))},[]);
 const shown=useMemo(()=>rows.filter(b=>{
  const text=(`${b.patient.name} ${b.patient.phone} ${b.patient.email||''} ${b.items.map(i=>i.test.name).join(' ')} ${b.slot} ${b.technician||''} ${b.status}`).toLowerCase();
  return text.includes(q.toLowerCase())&&(status==='ALL'||b.status===status)&&(payment==='ALL'||b.paymentStatus===payment)&&(source==='ALL'||b.source===source);
 }),[rows,q,status,payment,source]);
 const totalValue=shown.reduce((s,b)=>s+b.totalAmount,0);
 return <main style={{minHeight:'100vh',background:'#f4f8f6',padding:28,fontFamily:'Arial,sans-serif',color:'#12352f'}}><div style={{maxWidth:1450,margin:'0 auto'}}>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><div style={{fontSize:12,fontWeight:900,color:'#087f6f'}}>TG LABS • PHASE 2</div><h1 style={{marginBottom:6}}>Booking Management</h1><p style={{marginTop:0,color:'#657973'}}>Manage patient details, tests/packages, rescheduling, technician, payment, price, report and booking status.</p></div><a href="/admin" style={{color:'#087f6f',fontWeight:800}}>← Admin Dashboard</a></div>
  <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,margin:'18px 0'}}><div style={card}><b>{shown.length}</b><span> Matching bookings</span></div><div style={card}><b>₹{totalValue.toLocaleString('en-IN')}</b><span> Booking value</span></div><div style={card}><b>{shown.filter(x=>x.paymentStatus==='PAID').length}</b><span> Paid</span></div><div style={card}><b>{shown.filter(x=>x.status==='CONFIRMED').length}</b><span> Confirmed</span></div></section>
  <section style={{...card,display:'flex',gap:10,flexWrap:'wrap',alignItems:'center',marginBottom:18}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search patient, mobile, email, test, slot or technician..." style={{...field,flex:'1 1 360px'}}/><select style={field} value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All booking statuses</option>{['PENDING','CONFIRMED','CANCELLED','COMPLETED'].map(x=><option key={x}>{x}</option>)}</select><select style={field} value={payment} onChange={e=>setPayment(e.target.value)}><option value="ALL">All payments</option>{['PENDING','PAID','FAILED','REFUNDED'].map(x=><option key={x}>{x}</option>)}</select><select style={field} value={source} onChange={e=>setSource(e.target.value)}><option value="ALL">All sources</option><option>WEBSITE</option><option>ADMIN</option></select></section>
  <div style={{...card,overflowX:'auto'}}>{loading?'Loading…':<table style={{width:'100%',borderCollapse:'collapse',minWidth:1200}}><thead><tr>{['Patient','Age/Gender','Tests','Collection','Technician','Payment','Status','Report','Price','Action'].map(h=><th key={h} style={{textAlign:'left',padding:11,borderBottom:'1px solid #dce7e3',fontSize:12}}>{h}</th>)}</tr></thead><tbody>{shown.map(b=><tr key={b.id}><td style={{padding:11,borderBottom:'1px solid #edf2f0'}}><b>{b.patient.name}</b><br/><small>{b.patient.phone}{b.patient.email?<><br/>{b.patient.email}</>:null}</small></td><td>{b.patient.age??'—'} / {b.patient.gender||'—'}</td><td>{b.items.map(i=>i.test.name).join(', ')}</td><td>{new Date(b.collectionDate).toLocaleDateString('en-IN')}<br/><small>{b.mode} • {b.slot}</small></td><td>{b.technician||'—'}</td><td><b>{b.paymentStatus}</b></td><td>{b.status}</td><td>{b.reportName?'Uploaded':'Pending'}</td><td><b>₹{b.totalAmount}</b></td><td><a href={`/admin/bookings/${b.id}`} style={{display:'inline-block',padding:'9px 13px',borderRadius:9,background:'#087f6f',color:'#fff',fontWeight:800,textDecoration:'none'}}>Manage</a></td></tr>)}{!shown.length&&<tr><td colSpan={10} style={{padding:25,textAlign:'center'}}>No matching bookings.</td></tr>}</tbody></table>}</div>
 </div></main>
}
const card:React.CSSProperties={background:'#fff',border:'1px solid #dfe9e5',borderRadius:16,padding:16,boxShadow:'0 8px 24px rgba(12,71,61,.05)'};
